'use strict';
const D=window.SIMEC_DATA||{periodic:[],nonperiodic:[],planning:[]};
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fold=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const nf=v=>Number(v||0).toLocaleString('pt-BR'),pct=v=>(Number(v||0)*100).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
const MONTHS=['JANEIRO','FEVEREIRO','MARÇO','ABRIL','MAIO','JUNHO','JULHO','AGOSTO','SETEMBRO','OUTUBRO','NOVEMBRO','DEZEMBRO'];
const people=(window.SIMEC_EMPLOYEES?.list?.()||window.SIMEC_PEOPLE||[]).filter(p=>p?.id&&p?.name),peopleMap=new Map(people.map(p=>[String(p.id),p]));
const planningMap=new Map((D.planning||[]).map(p=>[String(p.id),p]));
const orders=[...(D.periodic||[]),...(D.nonperiodic||[])].map(r=>({...r,id:String(r.id)}));
let filters={month:MONTHS[new Date().getMonth()],week:'',area:'',supervisor:'',person:'',state:'',query:''};

const local=(prefix,id)=>{try{return localStorage.getItem(`simec-backlog-${prefix}-${id}`)}catch{return null}};
const parsePlanningWeek=value=>{const v=String(value||''),iso=v.match(/^(\d{4})-W(\d{2})$/),named=v.match(/Semana\s+(\d+)\s*\/\s*(\d{4})/i);return iso?v:named?`${named[2]}-W${String(named[1]).padStart(2,'0')}`:''};
function isoWeek(value){const date=new Date(String(value||'').slice(0,10)+'T12:00:00');if(Number.isNaN(date.valueOf()))return'';const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const start=new Date(Date.UTC(d.getUTCFullYear(),0,1)),week=Math.ceil((((d-start)/86400000)+1)/7);return`${d.getUTCFullYear()}-W${String(week).padStart(2,'0')}`;}
const weekLabel=v=>{const m=String(v||'').match(/^(\d{4})-W(\d{2})$/);return m?`Semana ${m[2]} / ${m[1]}`:'Sem semana';};
function assignments(order){try{const saved=JSON.parse(local('assignments',order.id)||'null');if(Array.isArray(saved)&&saved.length)return saved.map(a=>({...a,id:String(a.id)}));}catch{}const p=planningMap.get(order.id)||{},ids=String(p.laborIds||'').split(/\s*\|\s*|\s*,\s*/).filter(Boolean),hours=new Map();String(p.laborHours||'').split(/\s*\|\s*/).forEach(item=>{const m=item.match(/\(([^)]+)\)\s*:\s*([\d,.]+)h/i);if(m)hours.set(m[1],Number(m[2].replace(',','.'))||0);});return ids.map(id=>({id:String(id),hours:hours.get(String(id))||0}));}
function savedStage(order){return local('stage',order.id)||(planningMap.get(order.id)?.stage||'');}
function savedWeek(order){return parsePlanningWeek(local('week',order.id)||planningMap.get(order.id)?.scheduledWeek)||isoWeek(order.date);}
const savedDay=order=>local('day',order.id)||planningMap.get(order.id)?.scheduledDay||'';
const pointed=order=>{const value=fold(`${order.status||''} ${order.system||''}`);return value.includes('executada')||value.includes('encerrad');};
const programmed=order=>savedStage(order)==='04SC'||Boolean(parsePlanningWeek(local('week',order.id)||planningMap.get(order.id)?.scheduledWeek));
const stateOf=order=>pointed(order)?'done':programmed(order)?'waiting':'unplanned';
const stateLabel=value=>({done:'Apontada',waiting:'Aguardando apontamento',unplanned:'Sem programação'}[value]||value);
const ignoredTokens=new Set(['manutencao','producao','area','equipe','de','da','do','das','dos','e','ac2','operacao']);
const tokens=value=>new Set(fold(value).replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>1&&!ignoredTokens.has(x)));
const maintenancePeople=people.filter(p=>fold(p.type).includes('manutencao'));
const canonicalSupervisor=value=>{const name=fold(value);if(name.includes('vinicius'))return'Vinicius Franco Ramalho';if(name.includes('welliton')||name.includes('wellinton'))return'Welliton Julio da Costa';if(name.includes('ivan'))return'Ivan Candido';if(name.includes('sergio viana'))return'Sergio Viana';if(name.includes('orlando'))return'Orlando Borges';if(name.includes('marcos juds'))return'Marcos Juds Ferreira Leite';if(name.includes('xavier'))return'Xavier';return value&&!name.includes('nao inform')?value:'Não informado';};
const supervisorByArea=new Map([['manutencao eletrica fea fp lc','Vinicius Franco Ramalho'],['manutencao mecanica fea fp lc','Ivan Candido'],['despoeiramento dcs rmh','Welliton Julio da Costa'],['pcm engenharia de manutencao','Orlando Borges'],['gerencia engenharia de manutencao','Marcos Juds Ferreira Leite'],['pontes rolantes mecanica','Sergio Viana'],['refrigeracao','Xavier']]);
const teamGroups=[...new Map(maintenancePeople.map(p=>[p.area,p.area])).values()].map(area=>{const members=maintenancePeople.filter(p=>p.area===area),counts=new Map;for(const p of members){const supervisor=canonicalSupervisor(p.supervisor);if(supervisor!=='Não informado')counts.set(supervisor,(counts.get(supervisor)||0)+1);}const expected=supervisorByArea.get(fold(area))||[...counts].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Não informado';return{area,members,supervisor:expected,tokens:tokens(area)};});
const supervisorForArea=area=>teamGroups.find(g=>g.area===area)?.supervisor||'Não informado';
function inferredTeam(order){const source=tokens(`${order.area||''} ${order.specialty||''}`);let best={score:0,team:null};for(const team of teamGroups){let score=0;for(const token of source)if(team.tokens.has(token))score++;if(score>best.score)best={score,team};}return best.team?{area:best.team.area,supervisor:best.team.supervisor,score:best.score,inferred:true}:{area:'Não identificado',supervisor:'Não informado',score:0,inferred:true};}
function rowInfo(order){const labor=assignments(order),known=labor.map(a=>peopleMap.get(String(a.id))).filter(Boolean),unknown=labor.filter(a=>!a.thirdParty&&!peopleMap.has(String(a.id))),areas=[...new Set(known.map(p=>p.area).filter(Boolean))],fallback=inferredTeam(order),teamArea=areas.length===1?areas[0]:areas.length>1?'Equipes diferentes':fallback.area,supervisor=teamArea==='Equipes diferentes'?'Supervisores diferentes':supervisorForArea(teamArea)||fallback.supervisor,totalHours=labor.reduce((sum,a)=>sum+Number(a.hours||0),0)||Number(local('hours',order.id)||planningMap.get(order.id)?.plannedHours||0),state=stateOf(order),isProgrammed=programmed(order),isPointed=pointed(order);return{order,labor,known,unknown,teamArea,supervisor,totalHours,state,isProgrammed,isPointed,week:savedWeek(order),day:savedDay(order),stage:savedStage(order),inferred:!known.length,confidence:fallback.score};}
const allRows=orders.map(rowInfo);
function selected(){return allRows.filter(x=>(!filters.month||x.order.month===filters.month)&&(!filters.week||x.week===filters.week)&&(!filters.area||x.teamArea===filters.area)&&(!filters.supervisor||x.supervisor===filters.supervisor)&&(!filters.person||x.labor.some(a=>String(a.id)===filters.person))&&(!filters.state||x.state===filters.state)&&(!filters.query||x.known.some(p=>fold(`${p.name} ${p.id}`).includes(fold(filters.query)))));}
const distinct=(rows,key)=>[...new Set(rows.map(x=>typeof key==='function'?key(x):x[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR',{numeric:true}));
function optionList(values,current,all){return`<option value="">${all}</option>${values.map(v=>`<option value="${esc(v)}" ${String(v)===String(current)?'selected':''}>${esc(v)}</option>`).join('')}`;}
function renderFilters(){const monthRows=allRows.filter(x=>!filters.month||x.order.month===filters.month),areas=distinct(monthRows,'teamArea'),supervisors=distinct(monthRows.filter(x=>!filters.area||x.teamArea===filters.area),'supervisor'),professionals=[...new Map(monthRows.flatMap(x=>x.known).map(p=>[String(p.id),p])).values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')),weeks=distinct(monthRows,'week');$('#filters').innerHTML=`<label>Mês<select data-filter="month">${optionList(MONTHS.filter(m=>allRows.some(x=>x.order.month===m)),filters.month,'Todos os meses')}</select></label><label>Semana<select data-filter="week"><option value="">Todas as semanas</option>${weeks.map(v=>`<option value="${esc(v)}" ${v===filters.week?'selected':''}>${weekLabel(v)}</option>`).join('')}</select></label><label>Área / equipe<select data-filter="area">${optionList(areas,filters.area,'Todas as áreas')}</select></label><label>Supervisor<select data-filter="supervisor">${optionList(supervisors,filters.supervisor,'Todos os supervisores')}</select></label><label>Profissional<select data-filter="person"><option value="">Todos os profissionais</option>${professionals.map(p=>`<option value="${esc(p.id)}" ${filters.person===String(p.id)?'selected':''}>${esc(p.name)} · ${esc(p.id)}</option>`).join('')}</select></label><label>Colaborador por nome ou matrícula<input data-filter-query value="${esc(filters.query)}" placeholder="Ex.: Flavio ou 1863"></label><label>Situação<select data-filter="state"><option value="">Todas as situações</option>${['done','waiting','unplanned'].map(v=>`<option value="${v}" ${filters.state===v?'selected':''}>${stateLabel(v)}</option>`).join('')}</select></label><button type="button" id="clear-filters">Limpar filtros</button>`;$('#filters').onchange=e=>{const key=e.target.dataset.filter;if(!key)return;filters[key]=e.target.value;if(key==='month'){filters.week='';filters.area='';filters.supervisor='';filters.person='';}if(key==='area'){filters.supervisor='';filters.person='';}render();};const search=$('[data-filter-query]');search.oninput=e=>{filters.query=e.target.value;const pos=e.target.selectionStart;render();const next=$('[data-filter-query]');next.focus();next.setSelectionRange(pos,pos);};$('#clear-filters').onclick=()=>{filters={month:MONTHS[new Date().getMonth()],week:'',area:'',supervisor:'',person:'',state:'',query:''};render();};}
function renderKpis(rows){const scheduled=rows.filter(x=>x.state!=='unplanned'),done=rows.filter(x=>x.state==='done'),waiting=rows.filter(x=>x.state==='waiting'),unplanned=rows.filter(x=>x.state==='unplanned'),rate=scheduled.length?done.length/scheduled.length:0,hours=rows.reduce((sum,x)=>sum+x.totalHours,0);$('#kpis').innerHTML=[["Ordens da seleção",rows.length,'Total do período','#7027ad'],['Programadas',scheduled.length,'Com semana definida','#0066bd'],['Apontadas',done.length,'Executadas ou encerradas','#20a943'],['Aguardando',waiting.length,'Programadas sem encerramento','#e1b940'],['Sem programação',unplanned.length,'Precisam de tratamento','#8c99a5'],['Aderência',pct(rate),nf(hours)+' h previstas','#e5651a']].map(([a,b,c,color])=>`<article class="pointing-kpi" style="--accent:${color}"><span>${a}</span><strong>${typeof b==='number'?nf(b):b}</strong><small>${c}</small></article>`).join('');}
function renderWeekly(rows){const weeks=distinct(rows,'week');$('#weekly-chart').innerHTML=weeks.map(week=>{const group=rows.filter(x=>x.week===week),done=group.filter(x=>x.state==='done').length,waiting=group.filter(x=>x.state==='waiting').length,unplanned=group.length-done-waiting,rate=(done+waiting)?done/(done+waiting):0,max=Math.max(1,group.length);return`<div class="week-column"><strong class="week-rate">${pct(rate)}<small>${done} apontada(s) de ${done+waiting} programada(s)</small></strong><div class="week-stack" title="${done} apontadas · ${waiting} aguardando · ${unplanned} sem programação"><i class="done" style="height:${done/max*100}%"></i><i class="waiting" style="height:${waiting/max*100}%"></i><i class="unplanned" style="height:${unplanned/max*100}%"></i></div><span class="week-label">${weekLabel(week).replace(' / ','<small>')}</small><small>${group.length} ordem(ns)</small></span></div>`;}).join('')||'<div class="empty-state">Nenhuma ordem para o período selecionado.</div>'; }
function renderAttention(rows){const waiting=rows.filter(x=>x.state==='waiting'),unplanned=rows.filter(x=>x.state==='unplanned'),unknown=rows.filter(x=>x.unknown.length),noSupervisor=rows.filter(x=>x.supervisor==='Não informado'),overload=rows.filter(x=>x.totalHours>8);$('#attention-list').innerHTML=[["!",'Aguardando apontamento','Programadas e ainda não encerradas',waiting.length],['→','Sem programação','Ordens sem semana programada',unplanned.length],['?','Matrículas não localizadas','Conferir cadastro das equipes',unknown.length],['•','Supervisor não identificado','Conferir área e responsável',noSupervisor.length],['+','Acima de 8 horas','Conferir a carga planejada',overload.length]].map(([icon,title,note,value])=>`<div class="attention-item"><span class="attention-icon">${icon}</span><div><strong>${title}</strong><span>${note}</span></div><b class="attention-value">${nf(value)}</b></div>`).join('');}
function renderTeams(rows){const names=distinct(rows,'teamArea'),weeks=distinct(rows,'week');const groups=names.map(name=>{const data=rows.filter(x=>x.teamArea===name),scheduled=data.filter(x=>x.state!=='unplanned'),done=data.filter(x=>x.state==='done'),rate=scheduled.length?done.length/scheduled.length:0,supervisors=[...new Set(data.map(x=>x.supervisor))].join(' / ');return{name,data,scheduled,done,rate,supervisors};}).sort((a,b)=>b.data.length-a.data.length);$('#team-cards').innerHTML=groups.map(g=>`<article class="team-card"><div><h3>${esc(g.name)}</h3><p>${esc(g.supervisors)} · ${nf(g.data.length)} ordem(ns)</p></div><div class="team-result"><strong>${pct(g.rate)}</strong><small>${g.done.length} apontada(s)</small></div><div class="team-track"><i style="width:${g.rate*100}%"></i></div><div class="team-weeks">${weeks.map(w=>{const a=g.data.filter(x=>x.week===w),s=a.filter(x=>x.state!=='unplanned'),d=a.filter(x=>x.state==='done'),r=s.length?d.length/s.length:0;return`<span title="${weekLabel(w)} · ${pct(r)}"><i style="height:${r*100}%"></i><b>${String(w).slice(-2)}</b></span>`;}).join('')}</div></article>`).join('')||'<div class="empty-state">Nenhuma equipe para os filtros selecionados.</div>'; }
function renderAvailability(rows){const areas=new Map;for(const x of rows){for(const a of x.labor){const person=peopleMap.get(String(a.id)),area=person?.area||x.teamArea||'Não identificado',hours=Number(a.hours||0),g=areas.get(area)||{area,planned:0,pointed:0,people:new Set};g.planned+=hours;if(x.isPointed)g.pointed+=hours;if(person)g.people.add(String(person.id));areas.set(area,g)}}const groups=[...areas.values()].map(g=>({...g,missing:Math.max(0,g.planned-g.pointed)})).sort((a,b)=>b.planned-a.planned),max=Math.max(1,...groups.map(g=>g.planned));$('#availability-chart').innerHTML=groups.map(g=>`<article class="availability-row"><div><strong>${esc(g.area)}</strong><small>${g.people.size} colaborador(es) na seleção</small></div><div class="availability-bars"><span><b style="width:${g.planned/max*100}%" class="planned"></b><i>${g.planned.toLocaleString('pt-BR',{maximumFractionDigits:1})} h programadas</i></span><span><b style="width:${g.pointed/max*100}%" class="pointed"></b><i>${g.pointed.toLocaleString('pt-BR',{maximumFractionDigits:1})} h apontadas</i></span></div><div class="availability-missing"><strong>${g.missing.toLocaleString('pt-BR',{maximumFractionDigits:1})} h</strong><small>faltantes</small></div></article>`).join('')||'<div class="empty-state">Ainda não há horas distribuídas para os filtros selecionados.</div>'; }
function qualityIssues(rows){const issues=[],seen=new Set(),add=(key,type,text)=>{if(seen.has(key))return;seen.add(key);issues.push({type,text});};for(const person of maintenancePeople){const expected=supervisorForArea(person.area),actual=canonicalSupervisor(person.supervisor);if(expected!=='Não informado'&&actual!==expected)add(`person-${person.id}`,'Cadastro divergente',`${person.name} · ${person.id}: supervisor atual “${person.supervisor||'não informado'}”; esperado para ${person.area}: “${expected}”.`);}for(const x of rows){for(const a of x.unknown)add(`unknown-${a.id}`,'Matrícula não localizada',`Matrícula ${a.id} usada na OS ${x.order.id}.`);if(x.teamArea==='Equipes diferentes')add(`areas-${x.order.id}`,'Equipes diferentes',`OS ${x.order.id} possui profissionais de mais de uma área.`);if(x.supervisor==='Supervisores diferentes')add(`sup-${x.order.id}`,'Supervisores diferentes',`OS ${x.order.id} possui profissionais de supervisões diferentes.`);if(x.supervisor==='Não informado')add(`nosup-${x.teamArea}`,'Supervisor não informado',`${x.teamArea} precisa de supervisor no cadastro.`);if(x.inferred&&x.confidence<2)add(`area-${x.order.area}`,'Área para conferir',`${x.order.area||'Área vazia'} não encontrou uma correspondência segura na equipe atual.`);}return issues;}
function renderQuality(rows){const issues=qualityIssues(rows);$('#quality-count').textContent=nf(issues.length);$('#quality-list').innerHTML=issues.slice(0,100).map(x=>`<div class="quality-item"><span>${esc(x.type)}</span><small>${esc(x.text)}</small></div>`).join('')||'<div class="empty-state">Nenhuma divergência encontrada na seleção.</div>';}
function renderTable(rows){const sorted=[...rows].sort((a,b)=>`${a.week}|${a.order.area}|${a.order.id}`.localeCompare(`${b.week}|${b.order.area}|${b.order.id}`,'pt-BR',{numeric:true}));$('#pointing-body').innerHTML=sorted.slice(0,500).map(x=>{const activity=x.order.description||x.order.service||'Atividade não informada',labor=x.labor.map(a=>a.thirdParty?(a.name||'Terceiro'):(peopleMap.get(String(a.id))?.name||`Matrícula ${a.id}`)).join(' · ')||'—';return`<tr><td><strong>${weekLabel(x.week)}</strong><small>${esc(x.day||'—')}</small></td><td><strong>OS ${esc(x.order.id)}</strong><small>${esc(activity)}</small></td><td>${esc(x.order.area||'Não informada')}</td><td>${esc(x.teamArea)}${x.inferred?'<small>Sugestão pela área da ordem</small>':''}</td><td>${esc(x.supervisor)}</td><td>${esc(labor)}</td><td>${x.totalHours.toLocaleString('pt-BR')} h</td><td>${esc(x.stage||'Sem etapa')}</td><td><span class="pointing-badge ${x.state}">${stateLabel(x.state)}</span></td></tr>`;}).join('')||'<tr><td colspan="9" class="empty-state">Nenhuma ordem encontrada.</td></tr>';}
function exportRows(rows){return rows.map(x=>({semana:weekLabel(x.week),dia:x.day,ordem:x.order.id,atividade:x.order.description||x.order.service,areaOrdem:x.order.area,equipe:x.teamArea,supervisor:x.supervisor,profissionais:x.labor.map(a=>peopleMap.get(String(a.id))?.name||a.name||a.id).join(' | '),matriculas:x.labor.map(a=>a.id).join(' | '),horas:x.totalHours,etapa:x.stage,situacao:stateLabel(x.state)}));}
function render(){renderFilters();const rows=selected();$('#selection-count').textContent=`${nf(rows.length)} ordens na seleção`;renderKpis(rows);renderWeekly(rows);renderAttention(rows);renderAvailability(rows);renderTeams(rows);renderQuality(rows);renderTable(rows);$('#export-pointing').onclick=()=>window.exportTableXlsx(exportRows(rows),[['semana','Semana'],['dia','Dia'],['ordem','Ordem'],['atividade','Atividade'],['areaOrdem','Área da ordem'],['equipe','Equipe atual'],['supervisor','Supervisor'],['profissionais','Profissionais'],['matriculas','Matrículas'],['horas','Horas'],['etapa','Etapa'],['situacao','Apontamento']].map(([value,label])=>({value,label})),'Apontamentos','SIMEC-Controle-Apontamentos-'+new Date().toISOString().slice(0,10)+'.xlsx');}
$('#reload').onclick=()=>location.reload();$('#updated').textContent='Dados extraídos em '+new Date(D.generated||Date.now()).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});render();
