'use strict';
const D=window.SIMEC_DATA;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString('pt-BR'),pct=v=>(100*v).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
const MONTHS=['JANEIRO','FEVEREIRO','MARÇO','ABRIL','MAIO','JUNHO','JULHO','AGOSTO','SETEMBRO','OUTUBRO','NOVEMBRO','DEZEMBRO'];
const COLORS=['#28a745','#7f7c7c','#e1c16e','#004b87','#00a5df','#a387cf'];
const STATUS=['Executada','Não Executada','Pendente'];
const pages=['Periódicas','Ordens não periódicas','Consecução de Backlog'];
let page=0,filters={},tablePage=0;
const distinct=a=>[...new Set(a.filter(x=>x!==null&&x!==undefined&&x!==''))];
const groups=(rows,key)=>distinct(rows.map(r=>r[key])).sort((a,b)=>key==='month'?MONTHS.indexOf(a)-MONTHS.indexOf(b):String(a).localeCompare(String(b),'pt-BR',{numeric:true}));
const byFilter=rows=>rows.filter(r=>Object.entries(filters).every(([k,v])=>!v||String(r[k]??'')===v));
function measures(rows,non=false){const total=non?distinct(rows.map(r=>r.id)).length:rows.length;const done=non?distinct(rows.filter(r=>r.status===STATUS[0]).map(r=>r.id)).length:rows.filter(r=>r.status===STATUS[0]).length;const cancelled=distinct(rows.filter(r=>r.status===STATUS[1]).map(r=>r.id)).length;const pending=non?distinct(rows.filter(r=>r.status===STATUS[2]).map(r=>r.id)).length:total-done-cancelled;return{total,done,cancelled,pending,values:[done,cancelled,pending],rates:total?[done/total,cancelled/total,pending/total]:[0,0,0]};}
function legend(labels,colors=COLORS){return '<div class="legend">'+labels.map((l,i)=>`<span><i style="background:${colors[i%colors.length]}"></i>${esc(l)}</span>`).join('')+'</div>';}
function panel(title,body,full=false){return `<section class="panel ${full?'full':''}"><h2>${esc(title)}</h2>${body}</section>`;}
function gauge(title,value,target,color,count,total){const valid=total>0,v=Math.min(1,Math.max(0,value)),a=Math.PI*(1-target),x=150+112*Math.cos(a),y=135-112*Math.sin(a);return `<section class="panel gauge-panel"><h2>${esc(title)}</h2><svg class="gauge" viewBox="0 0 300 175" role="img" aria-label="${esc(title)}: ${valid?pct(value):'Sem dados'}"><path d="M38 135 A112 112 0 0 1 262 135" fill="none" stroke="#e9eef2" stroke-width="22"/><path d="M38 135 A112 112 0 0 1 262 135" fill="none" stroke="${color}" stroke-width="22" pathLength="100" stroke-dasharray="${v*100} 100"/><line x1="${150+(x-150)*.86}" y1="${135+(y-135)*.86}" x2="${150+(x-150)*1.14}" y2="${135+(y-135)*1.14}" stroke="#173c55" stroke-width="3"/><text x="150" y="123" text-anchor="middle" class="big">${valid?pct(value):'—'}</text><text x="31" y="163">0%</text><text x="242" y="163">100%</text></svg><div class="meta">Meta: ${pct(target)} · ${num(count)} de ${num(total)} ordens</div></section>`;}
function metric(title,value,note=''){return `<section class="panel"><h2>${esc(title)}</h2><div class="metric">${esc(value)}</div><div class="meta">${esc(note)}</div></section>`;}
function chart(title,labels,series,{percent=false,horizontal=false,stacked=false,full=false,filterKey=null,colors=COLORS,line=false}={}){
 if(!labels.length)return panel(title,'<div class="empty">Nenhum registro para os filtros selecionados.</div>',full);
 const W=horizontal?1000:Math.max(700,labels.length*90),H=horizontal?Math.max(240,labels.length*43+50):315,left=horizontal?255:55,right=horizontal?75:20,top=25,bottom=horizontal?25:55,iw=W-left-right,ih=H-top-bottom;
 const max=percent?1:Math.max(1,...labels.map((_,i)=>stacked?series.reduce((s,x)=>s+(x.values[i]||0),0):Math.max(...series.map(x=>x.values[i]||0))))*1.13;
 let svg=`<svg class="chart" style="min-width:${horizontal?760:Math.max(700,labels.length*70)}px" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(title)}">`;
 for(let i=0;i<=4;i++){const val=max*i/4;if(horizontal){const x=left+iw*i/4;svg+=`<line class="axis" x1="${x}" x2="${x}" y1="${top}" y2="${H-bottom}"/><text x="${x}" y="${H-4}" text-anchor="middle">${percent?pct(val):num(Math.round(val))}</text>`;}else{const y=top+ih-ih*i/4;svg+=`<line class="axis" x1="${left}" x2="${W-right}" y1="${y}" y2="${y}"/><text x="${left-10}" y="${y+4}" text-anchor="end">${percent?pct(val):num(Math.round(val))}</text>`;}}
 labels.forEach((label,i)=>{let cumulative=0;const slot=(horizontal?ih:iw)/labels.length,band=slot*.68;series.forEach((s,j)=>{const val=s.values[i]||0;let x,y,w,h;if(horizontal){x=left+iw*(stacked?cumulative:0)/max;y=top+i*slot+(slot-band)/2+(stacked?0:j*band/series.length);w=iw*val/max;h=stacked?band:band/series.length-1;}else{x=left+i*slot+(slot-band)/2+(stacked?0:j*band/series.length);y=top+ih-ih*(val+(stacked?cumulative:0))/max;w=stacked?band:band/series.length-2;h=ih*val/max;}const tip=`${label} · ${s.name}: ${percent?pct(val):num(val)}`;svg+=`<rect x="${x}" y="${y}" width="${Math.max(0,w)}" height="${Math.max(0,h)}" fill="${colors[j%colors.length]}" data-tip="${esc(tip)}" ${filterKey?`data-filter="${filterKey}" data-value="${esc(label)}" tabindex="0" role="button" aria-label="Filtrar ${esc(tip)}"`:''}><title>${esc(tip)}</title></rect>`;if(val>0&&!stacked&&!horizontal&&labels.length<=12)svg+=`<text x="${x+w/2}" y="${y-6}" text-anchor="middle" style="font-size:11px">${percent?pct(val):num(val)}</text>`;cumulative+=val;});if(horizontal){svg+=`<text x="${left-12}" y="${top+i*slot+slot/2+4}" text-anchor="end">${esc(String(label).slice(0,34))}</text>`;}else{const labelText=filterKey==='month'?label.slice(0,3):label;svg+=`<text x="${left+i*slot+slot/2}" y="${H-bottom+24}" text-anchor="middle">${esc(String(labelText).slice(0,20))}</text>`;}});
 if(line&&!horizontal){const points=labels.map((_,i)=>`${left+(i+.5)*iw/labels.length},${top+ih-ih*(series[0].values[i]||0)/max}`).join(' ');svg+=`<polyline points="${points}" fill="none" stroke="#00a5df" stroke-width="3"/>`;}
 svg+='</svg>';return panel(title,legend(series.map(x=>x.name),colors)+`<div class="chart-scroll">${svg}</div>`,full);
}
function statusChart(title,rows,key,non=false,opts={}){const labels=groups(rows,key),den=measures(rows,true).total;const series=STATUS.map((name,j)=>({name,values:labels.map(l=>{const m=measures(rows.filter(r=>r[key]===l),non);return opts.percent?(non?(den?m.values[j]/den:0):m.rates[j]):m.values[j];})}));return chart(title,labels,series,{...opts,filterKey:key});}
function buildFilters(){let rows,fields;if(page===0){rows=D.periodic;fields=[['month','Mês'],['type','Tipo de plano'],['specialty','Especialidade'],['period','Periodicidade']];}else if(page===1){rows=D.nonperiodic;fields=[['month','Mês'],['specialty','Especialidade'],['type','Criticidade']];}else if(page===2){rows=D.unified;fields=[['month','Mês'],['type','Tipo de manutenção'],['specialty','Especialidade'],['period','Periodicidade']];}else{rows=D.control.map(r=>({...r,month:D.schedule.find(a=>a.week===r.week)?.month}));fields=[['month','Mês'],['week','Semana'],['specialty','Responsável / setor']];}
 $('#filters').innerHTML=fields.map(([key,label])=>`<label>${label}<select data-key="${key}" aria-label="${label}"><option value="">Todos</option>${groups(rows,key).map(v=>`<option value="${esc(v)}" ${filters[key]===String(v)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`).join('')+'<button id="clear">Limpar filtros</button>';
 $('#filters').onchange=e=>{filters[e.target.dataset.key]=e.target.value;tablePage=0;renderContent();};$('#clear').onclick=()=>{filters={};tablePage=0;buildFilters();renderContent();};
}
function table(rows){const start=tablePage*50,cols=[['id','Ordem'],['plan','Plano'],['specialty','Especialidade'],['description','Descrição da manutenção'],['period','Periodicidade'],['system','Status no sistema']];return panel('Detalhes das ordens',`<div class="export-toolbar"><button id="export-excel" title="Exportar todas as ordens filtradas para Excel"><span aria-hidden="true">⇩</span> Exportar Excel</button><span>Todas as ${num(rows.length)} ordens da seleção</span></div><div class="table-scroll"><table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody>${rows.slice(start,start+50).map(r=>'<tr>'+cols.map(([k])=>`<td class="${k==='description'?'description':''}">${esc(r[k]??'—')}</td>`).join('')+'</tr>').join('')}</tbody></table></div><div class="table-tools"><span>${rows.length?start+1:0}–${Math.min(start+50,rows.length)} de ${num(rows.length)} ordens</span><div><button id="prev" ${!tablePage?'disabled':''}>Anterior</button> <button id="next" ${start+50>=rows.length?'disabled':''}>Próxima</button></div></div>`,true);}
function periodic(){const rows=byFilter(D.periodic),m=measures(rows),color=m.rates[0]>=.8?'#20a943':m.rates[0]>=.75?'#dbbd29':'#df3d3d';$('#count').textContent=num(m.total)+' ordens planejadas';let html='<div class="cards quantity-cards">'+metric('Ordens executadas',num(m.done),pct(m.rates[0])+' do total selecionado')+metric('Ordens não executadas',num(m.cancelled),pct(m.rates[1])+' do total selecionado')+metric('Ordens pendentes',num(m.pending),pct(m.rates[2])+' do total selecionado')+'</div><div class="cards">'+gauge('% Consecução',m.rates[0],.8,color,m.done,m.total)+gauge('% Ordens não executadas',m.rates[1],.1,'#7f7c7c',m.cancelled,m.total)+gauge('% Pendentes',m.rates[2],.05,'#d2af52',m.pending,m.total)+'</div><div class="charts">';html+=statusChart('Ritmo de consecução mensal',rows,'month',false,{percent:true,full:true});html+=table(rows)+'</div>';return html;}
function nonperiodic(){const rows=byFilter(D.nonperiodic),m=measures(rows,true);$('#count').textContent=num(m.total)+' ordens distintas';return '<div class="cards">'+metric('Ordens executadas',num(m.done),pct(m.rates[0])+' do total selecionado')+metric('Ordens não executadas',num(m.cancelled),pct(m.rates[1])+' do total selecionado')+metric('Ordens pendentes',num(m.pending),pct(m.rates[2])+' do total selecionado')+'</div><div class="charts">'+statusChart('Ritmo de consecução mensal',rows,'month',true,{percent:true,full:true})+statusChart('Quantidade de ordens por mês',rows,'month',true,{horizontal:true,stacked:true})+statusChart('Quantidade de ordens por especialidade',rows,'specialty',true,{horizontal:true,stacked:true})+'</div><p class="notice">No gráfico percentual, cada mês usa como denominador o total de ordens dos meses selecionados, conforme a fórmula “fixo” do Power BI.</p>';}
function backlog(){const rows=byFilter(D.unified),executed=rows.filter(r=>r.status==='Executada'),labels=groups(executed,'month'),types=groups(executed,'type');const ages=rows.filter(r=>r.classification==='NÃO PERIÓDICA'&&r.age!==null&&r.age!==''&&Number.isFinite(Number(r.age))).map(r=>Number(r.age));const average=ages.length?ages.reduce((a,b)=>a+b,0)/ages.length:null;const series=types.map(name=>({name,values:labels.map(l=>executed.filter(r=>r.month===l&&r.type===name).length)}));const shares=series.map(s=>({...s,values:s.values.map((v,i)=>v/series.reduce((sum,x)=>sum+x.values[i],0))}));const ids=new Set(rows.filter(r=>r.classification==='PERIÓDICA').map(r=>r.id)),nids=new Set(rows.filter(r=>r.classification==='NÃO PERIÓDICA').map(r=>r.id));$('#count').textContent=num(rows.length)+' registros unificados';return '<div class="notice">Os gráficos de execução foram reconstruídos contando ordens com situação “Executada”. Duas medidas referenciadas nesta página não têm definição no PBIX fornecido; a equivalência desses gráficos precisa de validação.</div><div class="cards">'+metric('Idade média · não periódicas',average===null?'—':average.toLocaleString('pt-BR',{maximumFractionDigits:1})+' dias','Média da idade registrada no Excel')+metric('Ordens executadas',num(executed.length),'Periódicas e não periódicas')+metric('Ordens no filtro',num(rows.length),'Base Unificado')+'</div><div class="charts">'+chart('Ritmo de consecução · periódicas e não periódicas',labels,shares,{percent:true,stacked:true,full:true,filterKey:'month',colors:['#004b87','#00a5df','#28a745','#e1c16e','#a387cf']})+chart('Backlog executado por tipo de ordem',labels,series,{horizontal:true,stacked:true,full:true,filterKey:'month',colors:['#004b87','#00a5df','#28a745','#e1c16e','#a387cf']})+statusChart('Consecução periódica por especialidade',D.periodic.filter(r=>ids.has(r.id)),'specialty',false,{percent:true,horizontal:true,stacked:true,full:true})+statusChart('Ordens não periódicas por especialidade',D.nonperiodic.filter(r=>nids.has(r.id)),'specialty',true,{horizontal:true,stacked:true,full:true})+'</div>';}
function preventive(){let schedule=D.schedule.filter(r=>(!filters.month||r.month===filters.month)&&(!filters.week||r.week===filters.week));const allowed=new Set(schedule.map(r=>r.week));let control=D.control.filter(r=>allowed.has(r.week)&&(!filters.specialty||r.specialty===filters.specialty));const weeks=new Set(control.map(r=>r.week));schedule=schedule.filter(r=>weeks.has(r.week));const sum=(rows,k)=>rows.reduce((s,r)=>s+Number(r[k]||0),0),done=sum(control,'done'),cancelled=sum(control,'cancelled'),pending=sum(control,'pending'),total=done+cancelled+pending,planned=sum(schedule,'planned'),outside=sum(schedule,'outside'),rate=total?done/total:0;const labels=groups(control,'week'),series=['done','cancelled','pending'].map((key,i)=>({name:['Executado','Reprogramado','Sem status'][i],values:labels.map(l=>sum(control.filter(r=>r.week===l),key))}));const adherence=labels.map((_,i)=>{const t=series.reduce((s,x)=>s+x.values[i],0);return t?series[0].values[i]/t:0;});$('#count').textContent=num(total)+' ordens · '+labels.length+' semanas';const den=planned+outside;const donut=`<div class="donut-wrap"><div class="donut" role="img" aria-label="Programado: ${num(planned)}. Fora da programação: ${num(outside)}" style="background:conic-gradient(#004b87 0 ${den?planned/den*100:0}%,#e1c16e 0 100%)"><div class="donut-center">${den?pct(planned/den):'—'}<small>programado</small></div></div><div>${legend(['Programado','Fora da programação'],['#004b87','#e1c16e'])}<p>${num(planned)} programadas</p><p>${num(outside)} fora da programação</p></div></div>`;return '<div class="notice">Fonte: cópia de PREVENTIVA SEM 37.xlsx, usada pelo relatório original. A consecução foi reconstruída como executado ÷ (executado + cancelado + sem status), pois a medida “% Consecução Correta” não consta no PBIX.</div><div class="cards">'+metric('Quantidade de ordens',num(total),'Executado + cancelado + sem status')+metric('Programado',num(planned),'Planilha 15')+metric('Fora da programação',num(outside),'Planilha 15')+'</div><div class="charts">'+gauge('% Consecução',rate,.8,rate>=.8?'#20a943':'#df3d3d',done,total)+gauge('% Atividades reprogramadas',total?cancelled/total:0,.1,'#7f7c7c',cancelled,total)+chart('Aderência à programação · preventiva',labels,[{name:'Consecução',values:adherence}],{percent:true,full:true,filterKey:'week',colors:['#004b87'],line:true})+panel('Aderência à programação · preventiva',donut,true)+chart('Ritmo de consecução por semana',labels,series,{full:true,filterKey:'week',colors:['#28a745','#7f7c7c','#e1c16e']})+'</div>';}
function renderContent(){ $('#title').textContent=pages[page];$('#content').innerHTML=[periodic,nonperiodic,backlog][page]();$('#method').innerHTML='<p>Fontes: Base de dados Power bi -.xlsm e Não_Periodicas_Power_bi_corrigido.xlsm. O site usa os valores salvos no Excel. Após editar e salvar as planilhas, execute ATUALIZAR_DASHBOARD e recarregue esta página.</p><ul><li>Periódicas: consecução = linhas executadas ÷ linhas planejadas; não executadas = ordens distintas não executadas ÷ linhas planejadas; pendentes = 1 − consecução − não executadas. Metas extraídas do PBIX: 80%, 10% e 5%.</li><li>Não periódicas: contagem distinta de ID_Ordem. O denominador dos percentuais mensais é o total dos meses selecionados (ALLSELECTED).</li><li>Backlog: idade média registrada na coluna Idade (Dias), sem recalcular em relação à data de hoje. As duas medidas de execução ausentes foram reconstruídas pelo status Executada.</li><li>Os filtros são compartilhados pelos gráficos da página. Clique nas barras para selecionar um mês ou especialidade. Limpar filtros restaura a visão completa.</li><li>Espaços nas extremidades dos rótulos foram removidos. A base contém '+Object.values(D.issues).reduce((a,b)=>a+b,0)+' erro(s) na coluna de tolerância, preservado(s) para conferência. Os arquivos originais não foram alterados.</li></ul>';if($('#export-excel'))$('#export-excel').onclick=()=>window.exportOrdersXlsx(byFilter(D.periodic),filters);if($('#prev'))$('#prev').onclick=()=>{tablePage--;renderContent();};if($('#next'))$('#next').onclick=()=>{tablePage++;renderContent();};}
function navigatePage(i){page=i;filters={};tablePage=0;$('#tabs').innerHTML=pages.map((p,j)=>`<button class="${i===j?'active':''}" aria-current="${i===j?'page':'false'}" data-page="${j}">${p}</button>`).join('');buildFilters();renderContent();}
$('#tabs').onclick=e=>{if(e.target.dataset.page!==undefined)navigatePage(Number(e.target.dataset.page));};
$('#reload').onclick=()=>location.reload();
document.addEventListener('click',e=>{const t=e.target.closest('[data-filter]');if(t){filters[t.dataset.filter]=t.dataset.value;tablePage=0;buildFilters();renderContent();}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-filter]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
document.addEventListener('mousemove',e=>{const t=e.target.closest('[data-tip]'),tip=$('#tooltip');if(t){tip.textContent=t.dataset.tip;tip.hidden=false;tip.style.left=Math.max(8,Math.min(e.clientX+14,window.innerWidth-330))+'px';tip.style.top=Math.max(8,Math.min(e.clientY+14,window.innerHeight-90))+'px';}else tip.hidden=true;});
$('#updated').textContent='Dados extraídos em '+new Date(D.generated).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});navigatePage(0);
