'use strict';
const D=window.SIMEC_DATA;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString('pt-BR'),pct=v=>(100*v).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
const MONTHS=['JANEIRO','FEVEREIRO','MARÇO','ABRIL','MAIO','JUNHO','JULHO','AGOSTO','SETEMBRO','OUTUBRO','NOVEMBRO','DEZEMBRO'];
const COLORS=['#28a745','#7f7c7c','#e1c16e','#004b87','#00a5df','#a387cf'];
const STATUS=['Executada','Não Executada','Pendente'];
const REPORT_ADMIN_IDS=['1863','2013'];
const canMonthlyReport=()=>REPORT_ADMIN_IDS.includes(String(window.SIMEC_ACCESS?.currentId?.()||sessionStorage.getItem('simec_portal_usuario_v1')||'').replace(/\D/g,''));
const visiblePages=()=>['Periódicas','Ordens não periódicas','Consecução de Backlog',...(canMonthlyReport()?['Resumo mensal']:[])];
let pages=visiblePages();
const defaultYear=String(new Date().getFullYear());
const rowValue=(r,k)=>k==='year'?String(r.date||'').slice(0,4):r[k];
let page=0,filters={year:defaultYear},tablePage=0,showPendingAreas=false;
const distinct=a=>[...new Set(a.filter(x=>x!==null&&x!==undefined&&x!==''))];
const groups=(rows,key)=>distinct(rows.map(r=>rowValue(r,key))).sort((a,b)=>key==='month'?MONTHS.indexOf(a)-MONTHS.indexOf(b):String(a).localeCompare(String(b),'pt-BR',{numeric:true}));
const byFilter=rows=>rows.filter(r=>Object.entries(filters).every(([k,v])=>Array.isArray(v)?(!v.length||v.includes(String(rowValue(r,k)??''))):(!v||String(rowValue(r,k)??'')===v)));
function measures(rows,non=false){const total=non?distinct(rows.map(r=>r.id)).length:rows.length;const done=non?distinct(rows.filter(r=>r.status===STATUS[0]).map(r=>r.id)).length:rows.filter(r=>r.status===STATUS[0]).length;const cancelled=distinct(rows.filter(r=>r.status===STATUS[1]).map(r=>r.id)).length;const pending=non?distinct(rows.filter(r=>r.status===STATUS[2]).map(r=>r.id)).length:total-done-cancelled;return{total,done,cancelled,pending,values:[done,cancelled,pending],rates:total?[done/total,cancelled/total,pending/total]:[0,0,0]};}
function legend(labels,colors=COLORS){return '<div class="legend">'+labels.map((l,i)=>`<span><i style="background:${colors[i%colors.length]}"></i>${esc(l)}</span>`).join('')+'</div>';}
function panel(title,body,full=false){return `<section class="panel ${full?'full':''}"><h2>${esc(title)}</h2>${body}</section>`;}
function gauge(title,value,target,color,count,total,action=false){const valid=total>0,v=Math.min(1,Math.max(0,value)),a=Math.PI*(1-target),x=150+112*Math.cos(a),y=135-112*Math.sin(a);return `<section class="panel gauge-panel ${action?'pending-action':''}" ${action?'data-pending-areas tabindex="0" role="button" title="Mostrar pendentes por área"':''}><h2>${esc(title)}</h2><svg class="gauge" viewBox="0 0 300 175" role="img" aria-label="${esc(title)}: ${valid?pct(value):'Sem dados'}"><path d="M38 135 A112 112 0 0 1 262 135" fill="none" stroke="#e9eef2" stroke-width="22"/><path d="M38 135 A112 112 0 0 1 262 135" fill="none" stroke="${color}" stroke-width="22" pathLength="100" stroke-dasharray="${v*100} 100"/><line x1="${150+(x-150)*.86}" y1="${135+(y-135)*.86}" x2="${150+(x-150)*1.14}" y2="${135+(y-135)*1.14}" stroke="#173c55" stroke-width="3"/><text x="150" y="123" text-anchor="middle" class="big">${valid?pct(value):'—'}</text><text x="31" y="163">0%</text><text x="242" y="163">100%</text></svg><div class="meta">Meta: ${pct(target)} · ${num(count)} de ${num(total)} ordens</div></section>`;}
function metric(title,value,note='',action=false){return `<section class="panel ${action?'pending-action':''}" ${action?'data-pending-areas tabindex="0" role="button" title="Mostrar pendentes por área"':''}><h2>${esc(title)}</h2><div class="metric">${esc(value)}</div><div class="meta">${esc(note)}</div></section>`;}
function chart(title,labels,series,{percent=false,horizontal=false,stacked=false,full=false,filterKey=null,colors=COLORS,line=false}={}){
 if(!labels.length)return panel(title,'<div class="empty">Nenhum registro para os filtros selecionados.</div>',full);
 const W=horizontal?1000:Math.max(700,labels.length*90),H=horizontal?Math.max(240,labels.length*43+50):315,left=horizontal?255:55,right=horizontal?75:20,top=25,bottom=horizontal?25:55,iw=W-left-right,ih=H-top-bottom;
 const max=percent?1:Math.max(1,...labels.map((_,i)=>stacked?series.reduce((s,x)=>s+(x.values[i]||0),0):Math.max(...series.map(x=>x.values[i]||0))))*1.13;
 let svg=`<svg class="chart" style="min-width:${horizontal?760:Math.max(700,labels.length*70)}px" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(title)}">`;
 for(let i=0;i<=4;i++){const val=max*i/4;if(horizontal){const x=left+iw*i/4;svg+=`<line class="axis" x1="${x}" x2="${x}" y1="${top}" y2="${H-bottom}"/><text x="${x}" y="${H-4}" text-anchor="middle">${percent?pct(val):num(Math.round(val))}</text>`;}else{const y=top+ih-ih*i/4;svg+=`<line class="axis" x1="${left}" x2="${W-right}" y1="${y}" y2="${y}"/><text x="${left-10}" y="${y+4}" text-anchor="end">${percent?pct(val):num(Math.round(val))}</text>`;}}
 labels.forEach((label,i)=>{let cumulative=0;const slot=(horizontal?ih:iw)/labels.length,band=slot*.68;series.forEach((s,j)=>{const val=s.values[i]||0;let x,y,w,h;if(horizontal){x=left+iw*(stacked?cumulative:0)/max;y=top+i*slot+(slot-band)/2+(stacked?0:j*band/series.length);w=iw*val/max;h=stacked?band:band/series.length-1;}else{x=left+i*slot+(slot-band)/2+(stacked?0:j*band/series.length);y=top+ih-ih*(val+(stacked?cumulative:0))/max;w=stacked?band:band/series.length-2;h=ih*val/max;}const tip=`${label} · ${s.name}: ${percent?pct(val):num(val)}`;svg+=`<rect x="${x}" y="${y}" width="${Math.max(0,w)}" height="${Math.max(0,h)}" fill="${colors[j%colors.length]}" data-tip="${esc(tip)}" ${filterKey?`data-filter="${filterKey}" data-value="${esc(label)}" tabindex="0" role="button" aria-label="Filtrar ${esc(tip)}"`:''}><title>${esc(tip)}</title></rect>`;if(val>0&&percent){const labelX=horizontal?x+w/2:x+w/2,labelY=horizontal?y+h/2+4:(stacked?y+h/2+4:y-6);svg+=`<text x="${labelX}" y="${labelY}" text-anchor="middle" style="font-size:10px;font-weight:700;fill:#173347;paint-order:stroke;stroke:#fff;stroke-width:3px;stroke-linejoin:round;pointer-events:none">${pct(val)}</text>`;}else if(val>0&&!stacked&&!horizontal&&labels.length<=12){svg+=`<text x="${x+w/2}" y="${y-6}" text-anchor="middle" style="font-size:11px">${num(val)}</text>`;}cumulative+=val;});if(horizontal){svg+=`<text x="${left-12}" y="${top+i*slot+slot/2+4}" text-anchor="end">${esc(String(label).slice(0,34))}</text>`;}else{const labelText=filterKey==='month'?label.slice(0,3):label;svg+=`<text x="${left+i*slot+slot/2}" y="${H-bottom+24}" text-anchor="middle">${esc(String(labelText).slice(0,20))}</text>`;}});
 if(line&&!horizontal){const points=labels.map((_,i)=>`${left+(i+.5)*iw/labels.length},${top+ih-ih*(series[0].values[i]||0)/max}`).join(' ');svg+=`<polyline points="${points}" fill="none" stroke="#00a5df" stroke-width="3"/>`;}
 svg+='</svg>';return panel(title,legend(series.map(x=>x.name),colors)+`<div class="chart-scroll">${svg}</div>`,full);
}
function statusChart(title,rows,key,non=false,opts={}){const labels=groups(rows,key),den=measures(rows,true).total;const series=STATUS.map((name,j)=>({name,values:labels.map(l=>{const m=measures(rows.filter(r=>r[key]===l),non);return opts.percent?(opts.normalizeGroup?m.rates[j]:(non?(den?m.values[j]/den:0):m.rates[j])):m.values[j];})}));return chart(title,labels,series,{...opts,filterKey:key});}
function filterControl(rows,key,label){const values=groups(rows,key);if(key!=='area')return `<label>${label}<select data-key="${key}" aria-label="${label}"><option value="">Todos</option>${values.map(v=>`<option value="${esc(v)}" ${filters[key]===String(v)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;const selected=Array.isArray(filters[key])?filters[key]:(filters[key]?[String(filters[key])]:[]),caption=!selected.length?'Todas as áreas':selected.length===1?selected[0]:`${selected.length} áreas selecionadas`;return `<fieldset class="multi-filter"><legend>${esc(label)}</legend><div class="multi-filter-control"><button type="button" class="multi-filter-summary" data-multi-toggle="${key}" aria-expanded="false">${esc(caption)}</button><div class="multi-filter-menu" data-multi-menu="${key}" hidden>${values.map(v=>`<label class="multi-filter-option"><input type="checkbox" data-multi-key="${key}" data-multi-value="${esc(v)}" ${selected.includes(String(v))?'checked':''}><span>${esc(v)}</span></label>`).join('')}</div></div></fieldset>`;}
function buildFilters(){let rows,fields;if(page===0){rows=D.periodic;fields=[['month','Mês'],['type','Tipo de plano'],['area','Área do plano'],['period','Periodicidade']];}else if(page===1){rows=D.nonperiodic;fields=[['month','Mês'],['area','Área correlacionada'],['type','Tipo de manutenção']];}else if(page===2){rows=D.unified;fields=[['classification','Origem da ordem'],['month','Mês'],['type','Tipo de manutenção'],['area','Área'],['period','Periodicidade']];}else if(page===3){rows=D.periodic;fields=[['month','Mês']];}else{rows=D.control.map(r=>({...r,month:D.schedule.find(a=>a.week===r.week)?.month}));fields=[['month','Mês'],['week','Semana'],['specialty','Responsável / setor']];}
 const years=groups(rows,'year');if(!years.includes(defaultYear))years.push(defaultYear);years.sort((a,b)=>Number(b)-Number(a));
 const yearRows=rows.filter(r=>rowValue(r,'year')===filters.year);
 $('#filters').innerHTML=`<label>Ano<select data-key="year" aria-label="Ano">${years.map(y=>`<option value="${esc(y)}" ${filters.year===y?'selected':''}>${esc(y)}</option>`).join('')}</select></label>`+fields.map(([key,label])=>filterControl(yearRows,key,label)).join('')+'<button id="clear">Limpar filtros</button>';
 const multiToggle=$('#filters').querySelector('[data-multi-toggle]');if(multiToggle)multiToggle.onclick=()=>{const menu=$('#filters').querySelector(`[data-multi-menu="${multiToggle.dataset.multiToggle}"]`),open=menu.hidden;menu.hidden=!open;multiToggle.setAttribute('aria-expanded',String(open));};$('#filters').onchange=e=>{const multiKey=e.target.dataset.multiKey;if(multiKey){const values=[...$('#filters').querySelectorAll(`[data-multi-key="${multiKey}"]:checked`)].map(input=>input.dataset.multiValue);filters[multiKey]=values;const summary=$('#filters').querySelector(`[data-multi-toggle="${multiKey}"]`);if(summary)summary.textContent=!values.length?'Todas as áreas':values.length===1?values[0]:`${values.length} áreas selecionadas`;tablePage=0;renderContent();return;}const key=e.target.dataset.key;if(!key)return;if(key==='year'){filters={year:e.target.value};if(page===3)filters.month=groups(D.periodic.filter(r=>rowValue(r,'year')===filters.year),'month').at(-1)||'';buildFilters()}else filters[key]=e.target.value;tablePage=0;renderContent();};$('#clear').onclick=()=>{filters={year:defaultYear};if(page===3)filters.month=groups(D.periodic.filter(r=>rowValue(r,'year')===defaultYear),'month').at(-1)||'';tablePage=0;buildFilters();renderContent();};

}
function table(rows){const start=tablePage*50,cols=[['id','Ordem'],['plan','Plano'],['area','Área do plano'],['specialty','Especialidade técnica'],['description','Descrição da manutenção'],['period','Periodicidade'],['system','Status no sistema']];return panel('Detalhes das ordens',`<div class="export-toolbar"><button id="export-excel" title="Exportar todas as ordens filtradas para Excel"><span aria-hidden="true">⇩</span> Exportar Excel</button><span>Todas as ${num(rows.length)} ordens da seleção</span></div><div class="table-scroll"><table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody>${rows.slice(start,start+50).map(r=>'<tr>'+cols.map(([k])=>`<td class="${k==='description'?'description':''}">${esc(r[k]??'—')}</td>`).join('')+'</tr>').join('')}</tbody></table></div><div class="table-tools"><span>${rows.length?start+1:0}–${Math.min(start+50,rows.length)} de ${num(rows.length)} ordens</span><div><button id="prev" ${!tablePage?'disabled':''}>Anterior</button> <button id="next" ${start+50>=rows.length?'disabled':''}>Próxima</button></div></div>`,true);}
function pendingAreaTable(rows){const pending=rows.filter(r=>r.status==='Pendente'),map=new Map();for(const r of pending){const area=String(r.area||'Não informado').trim()||'Não informado',g=map.get(area)||{area,periodic:new Set(),nonperiodic:new Set()};(r.classification==='NÃO PERIÓDICA'?g.nonperiodic:g.periodic).add(String(r.id));map.set(area,g)}const data=[...map.values()].map(g=>({area:g.area,periodic:g.periodic.size,nonperiodic:g.nonperiodic.size,total:g.periodic.size+g.nonperiodic.size})).sort((a,b)=>b.total-a.total||a.area.localeCompare(b.area,'pt-BR'));return panel('Ordens pendentes por área',`<p class="pending-table-note">Tabela calculada com os mesmos filtros da tela. Clique novamente em Pendentes para ocultar.</p><div class="table-scroll"><table><thead><tr><th>Área</th><th>Periódicas</th><th>Não periódicas</th><th>Total pendente</th><th>Participação</th></tr></thead><tbody>${data.map(g=>`<tr><td><strong>${esc(g.area)}</strong></td><td>${num(g.periodic)}</td><td>${num(g.nonperiodic)}</td><td><strong>${num(g.total)}</strong></td><td>${pct(pending.length?g.total/pending.length:0)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhuma ordem pendente para os filtros selecionados.</td></tr>'}</tbody></table></div>`,true)}
function periodic(){const rows=byFilter(D.periodic),m=measures(rows),color=m.rates[0]>=.8?'#20a943':m.rates[0]>=.75?'#dbbd29':'#df3d3d';$('#count').textContent=num(m.total)+' ordens planejadas';let html='<div class="cards quantity-cards">'+metric('Ordens executadas',num(m.done),pct(m.rates[0])+' do total selecionado')+metric('Ordens não executadas',num(m.cancelled),pct(m.rates[1])+' do total selecionado')+metric('Ordens pendentes',num(m.pending),'Clique para ver as áreas · '+pct(m.rates[2]),true)+'</div><div class="cards">'+gauge('% Consecução',m.rates[0],.8,color,m.done,m.total)+gauge('% Ordens não executadas',m.rates[1],.1,'#7f7c7c',m.cancelled,m.total)+gauge('% Pendentes',m.rates[2],.05,'#d2af52',m.pending,m.total,true)+'</div>'+(showPendingAreas?pendingAreaTable(rows):'')+'<div class="charts">';html+=statusChart('Ritmo de consecução mensal',rows,'month',false,{percent:true,full:true});html+=table(rows)+'</div>';return html;}
function nonperiodic(){const rows=byFilter(D.nonperiodic),m=measures(rows,true);$('#count').textContent=num(m.total)+' ordens distintas';return '<div class="cards">'+metric('Ordens executadas',num(m.done),pct(m.rates[0])+' do total selecionado')+metric('Ordens não executadas',num(m.cancelled),pct(m.rates[1])+' do total selecionado')+metric('Ordens pendentes',num(m.pending),'Clique para ver as áreas · '+pct(m.rates[2]),true)+'</div>'+(showPendingAreas?pendingAreaTable(rows):'')+'<div class="charts">'+statusChart('Ritmo de consecução mensal',rows,'month',true,{percent:true,stacked:true,normalizeGroup:true,full:true})+statusChart('Quantidade de ordens por mês',rows,'month',true,{horizontal:true,stacked:true})+statusChart('Quantidade de ordens por área',rows,'area',true,{horizontal:true,stacked:true})+'</div><p class="notice">Cada coluna do ritmo mensal representa 100% das ordens não periódicas daquele mês, divididas em executadas, não executadas e pendentes. A área é correlacionada com a Descrição do Plano da base periódica.</p>';}
function backlog(){const rows=byFilter(D.unified),periodicRows=rows.filter(r=>r.classification==='PERIÓDICA'),nonperiodicRows=rows.filter(r=>r.classification==='NÃO PERIÓDICA'),executed=rows.filter(r=>r.status==='Executada'),m=measures(rows,true),labels=groups(rows,'month'),executedTypes=groups(executed,'type');const ages=nonperiodicRows.filter(r=>r.age!==null&&r.age!==''&&Number.isFinite(Number(r.age))).map(r=>Number(r.age)),average=ages.length?ages.reduce((a,b)=>a+b,0)/ages.length:null;const composition=[{name:'Planos periódicos',classification:'PERIÓDICA'},{name:'Ordens não periódicas',classification:'NÃO PERIÓDICA'}].map(item=>({name:item.name,values:labels.map(month=>{const monthRows=rows.filter(r=>r.month===month),unique=new Set(monthRows.map(r=>`${r.classification}|${r.id}`)).size,selected=new Set(monthRows.filter(r=>r.classification===item.classification).map(r=>String(r.id))).size;return unique?selected/unique:0})}));const executedVolume=executedTypes.map(type=>({name:type,values:labels.map(month=>executed.filter(r=>r.month===month&&r.type===type).length)}));$('#count').textContent=num(m.total)+' ordens no backlog consolidado';return '<div class="notice">Consolidação direta do arquivo principal: Base dados (periódicas) + Base dados_N Periodicas (não periódicas). A aba Unificado não é usada como fonte.</div><div class="cards quantity-cards">'+metric('Ordens periódicas',num(periodicRows.length),pct(rows.length?periodicRows.length/rows.length:0)+' do volume')+metric('Ordens não periódicas',num(nonperiodicRows.length),pct(rows.length?nonperiodicRows.length/rows.length:0)+' do volume')+metric('Volume total',num(m.total),'Periódicas + não periódicas')+metric('Idade média · não periódicas',average===null?'—':average.toLocaleString('pt-BR',{maximumFractionDigits:1})+' dias','Ordens da seleção')+'</div><div class="charts">'+chart('Composição mensal · planos periódicos x ordens não periódicas',labels,composition,{percent:true,stacked:true,full:true,filterKey:'month',colors:['#004b87','#e5651a']})+chart('Backlog executado por tipo de ordem',labels,executedVolume,{horizontal:true,stacked:true,full:true,filterKey:'month',colors:['#004b87','#202ca6','#00a5df','#a387cf','#e1c16e','#ef6c32','#28a745','#7f7c7c']})+statusChart('Quantidade por situação e área',rows,'area',true,{horizontal:true,stacked:true,full:true})+statusChart('Ritmo de consecução por área',rows,'area',true,{percent:true,stacked:true,normalizeGroup:true,full:true})+'</div>';}
function preventive(){let schedule=D.schedule.filter(r=>(!filters.month||r.month===filters.month)&&(!filters.week||r.week===filters.week));const allowed=new Set(schedule.map(r=>r.week));let control=D.control.filter(r=>allowed.has(r.week)&&(!filters.specialty||r.specialty===filters.specialty));const weeks=new Set(control.map(r=>r.week));schedule=schedule.filter(r=>weeks.has(r.week));const sum=(rows,k)=>rows.reduce((s,r)=>s+Number(r[k]||0),0),done=sum(control,'done'),cancelled=sum(control,'cancelled'),pending=sum(control,'pending'),total=done+cancelled+pending,planned=sum(schedule,'planned'),outside=sum(schedule,'outside'),rate=total?done/total:0;const labels=groups(control,'week'),series=['done','cancelled','pending'].map((key,i)=>({name:['Executado','Reprogramado','Sem status'][i],values:labels.map(l=>sum(control.filter(r=>r.week===l),key))}));const adherence=labels.map((_,i)=>{const t=series.reduce((s,x)=>s+x.values[i],0);return t?series[0].values[i]/t:0;});$('#count').textContent=num(total)+' ordens · '+labels.length+' semanas';const den=planned+outside;const donut=`<div class="donut-wrap"><div class="donut" role="img" aria-label="Programado: ${num(planned)}. Fora da programação: ${num(outside)}" style="background:conic-gradient(#004b87 0 ${den?planned/den*100:0}%,#e1c16e 0 100%)"><div class="donut-center">${den?pct(planned/den):'—'}<small>programado</small></div></div><div>${legend(['Programado','Fora da programação'],['#004b87','#e1c16e'])}<p>${num(planned)} programadas</p><p>${num(outside)} fora da programação</p></div></div>`;return '<div class="notice">Fonte: cópia de PREVENTIVA SEM 37.xlsx, usada pelo relatório original. A consecução foi reconstruída como executado ÷ (executado + cancelado + sem status), pois a medida “% Consecução Correta” não consta no PBIX.</div><div class="cards">'+metric('Quantidade de ordens',num(total),'Executado + cancelado + sem status')+metric('Programado',num(planned),'Planilha 15')+metric('Fora da programação',num(outside),'Planilha 15')+'</div><div class="charts">'+gauge('% Consecução',rate,.8,rate>=.8?'#20a943':'#df3d3d',done,total)+gauge('% Atividades reprogramadas',total?cancelled/total:0,.1,'#7f7c7c',cancelled,total)+chart('Aderência à programação · preventiva',labels,[{name:'Consecução',values:adherence}],{percent:true,full:true,filterKey:'week',colors:['#004b87'],line:true})+panel('Aderência à programação · preventiva',donut,true)+chart('Ritmo de consecução por semana',labels,series,{full:true,filterKey:'week',colors:['#28a745','#7f7c7c','#e1c16e']})+'</div>';}

const reportKey=()=>`simec_monthly_management_${filters.year}_${filters.month||'sem_mes'}`;
const reportPercent=v=>(100*(Number(v)||0)).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
const reportSignal=(value,target,lowerIsBetter=false)=>((lowerIsBetter?value<=target:value>=target)?'🟢':'🔴');
function uniqueOrders(rows){const map=new Map();for(const r of rows)map.set(`${r.classification||''}|${r.id}`,r);return [...map.values()];}
function monthlyReportData(){
 const year=filters.year,month=filters.month||groups(D.periodic.filter(r=>rowValue(r,'year')===year),'month').at(-1)||'';
 const periodicRows=D.periodic.filter(r=>rowValue(r,'year')===year&&r.month===month),periodicMeasures=measures(periodicRows);
 const unifiedRows=uniqueOrders(D.unified.filter(r=>rowValue(r,'year')===year&&r.month===month));
 const executed=unifiedRows.filter(r=>r.status==='Executada'),executedPeriodic=executed.filter(r=>r.classification==='PERIÓDICA'),executedNonperiodic=executed.filter(r=>r.classification==='NÃO PERIÓDICA');
 const availableMonths=groups(D.periodic.filter(r=>rowValue(r,'year')===year),'month'),selectedIndex=availableMonths.indexOf(month),comparisonMonths=availableMonths.slice(Math.max(0,(selectedIndex<0?availableMonths.length-1:selectedIndex)-3),(selectedIndex<0?availableMonths.length-1:selectedIndex)+1);
 const comparison=comparisonMonths.map(label=>({label,metrics:measures(D.periodic.filter(r=>rowValue(r,'year')===year&&r.month===label))}));
 const areaNames=groups(periodicRows,'area');
 const areas=areaNames.map(area=>({area,metrics:measures(periodicRows.filter(r=>r.area===area))})).sort((a,b)=>b.metrics.rates[0]-a.metrics.rates[0]||a.area.localeCompare(b.area,'pt-BR'));
 const nonperiodicTypes=groups(executedNonperiodic,'type').map(type=>({type,count:executedNonperiodic.filter(r=>r.type===type).length})).sort((a,b)=>b.count-a.count);
 return{year,month,periodicRows,periodicMeasures,unifiedRows,executed,executedPeriodic,executedNonperiodic,comparison,areas,nonperiodicTypes};
}
function managementText(){try{return localStorage.getItem(reportKey())||''}catch{return''}}
function reportBody(data,management,plain=false){
 const bullet=plain?'• ':'<li>',end=plain?'\n':'</li>',sub=plain?'  ◦ ':'<li>',subEnd=plain?'\n':'</li>';
 const line=plain?'\n':'<hr>',heading=(icon,text)=>plain?`${icon} ${text}\n`:`<h3>${icon} ${esc(text)}</h3>`;
 const p=plain?reportPercent:data=>reportPercent(data);
 let out=plain?`Indicadores de Consecução Manutenção Aciaria 2 – Fechamento de ${data.month}/${data.year}\n\n`:`<h1>Indicadores de Consecução Manutenção Aciaria 2 – Fechamento de ${esc(data.month)}/${esc(data.year)}</h1>`;
 out+=heading('📊','Comparativo de Execução')+(plain?'':'<ul>');for(const item of data.comparison){out+=`${bullet}${item.label}: ${p(item.metrics.rates[0])} ${reportSignal(item.metrics.rates[0],.8)}${end}`}out+=plain?line:'</ul>'+line;
 out+=heading('🔍',`Detalhamento de ${data.month}`)+(plain?'':'<ul>')+`${bullet}Ordens Executadas: ${p(data.periodicMeasures.rates[0])} ${reportSignal(data.periodicMeasures.rates[0],.8)}${end}${bullet}Ordens Canceladas: ${p(data.periodicMeasures.rates[1])} ${reportSignal(data.periodicMeasures.rates[1],.1,true)}${end}${bullet}Ordens Pendentes: ${p(data.periodicMeasures.rates[2])} ${reportSignal(data.periodicMeasures.rates[2],.05,true)}${end}`+(plain?line:'</ul>'+line);
 const total=data.executed.length,planRate=total?data.executedPeriodic.length/total:0,npRate=total?data.executedNonperiodic.length/total:0;
 out+=heading('⭐','Volume e Perfil de Execução')+(plain?'':'<ul>')+`${bullet}Total de Ordens Executadas: ${num(total)} ordens${end}${bullet}Ordens de Planos: ${p(planRate)} (${num(data.executedPeriodic.length)} ordens)${end}${bullet}Ordens Não Periódicas: ${p(npRate)} (${num(data.executedNonperiodic.length)} ordens)${end}`;
 if(data.nonperiodicTypes.length){out+=plain?'':'<ul>';for(const item of data.nonperiodicTypes)out+=`${sub}${item.type}: ${p(data.executedNonperiodic.length?item.count/data.executedNonperiodic.length:0)} (${num(item.count)} ordens)${subEnd}`;out+=plain?'':'</ul>'}out+=plain?line:'</ul>'+line;
 out+=heading('⚙️','Detalhamento por Área')+(plain?'':'<ul>');for(const item of data.areas){out+=plain?`${bullet}${item.area}\n${sub}Consecução: ${p(item.metrics.rates[0])} ${reportSignal(item.metrics.rates[0],.8)}${subEnd}${sub}Canceladas: ${p(item.metrics.rates[1])} ${reportSignal(item.metrics.rates[1],.1,true)}${subEnd}${sub}Pendentes: ${p(item.metrics.rates[2])} ${reportSignal(item.metrics.rates[2],.05,true)}${subEnd}`:`<li><strong>${esc(item.area)}</strong><ul><li>Consecução: ${p(item.metrics.rates[0])} ${reportSignal(item.metrics.rates[0],.8)}</li><li>Canceladas: ${p(item.metrics.rates[1])} ${reportSignal(item.metrics.rates[1],.1,true)}</li><li>Pendentes: ${p(item.metrics.rates[2])} ${reportSignal(item.metrics.rates[2],.05,true)}</li></ul></li>`}out+=plain?line:'</ul>'+line;
 out+=heading('🤝','Gestão')+(plain?(management||'Sem observações de gestão.'):`<p class="management-copy">${esc(management||'Sem observações de gestão.').replace(/\n/g,'<br>')}</p>`);return out;
}
function monthlyReport(){
 if(!canMonthlyReport()){page=0;return periodic()}
 const data=monthlyReportData(),management=managementText();$('#count').textContent=`Fechamento de ${data.month||'—'}/${data.year}`;
 return `<section class="monthly-report-builder"><div class="report-toolbar"><div><span class="report-lock">Acesso exclusivo · matrículas 1863 e 2013</span><h2>Gerador do resumo mensal</h2><p>Os indicadores abaixo são preenchidos automaticamente com os dados do mês selecionado.</p></div><div class="report-actions"><button id="copy-monthly-report">Copiar para e-mail</button><button id="print-monthly-report">Gerar PDF</button><button id="download-monthly-report" class="primary-report">Baixar Word</button></div></div><label class="management-editor"><strong>Gestão · campo editável</strong><textarea id="management-text" rows="8" placeholder="Escreva aqui as observações, avanços, riscos e próximas ações da gestão.">${esc(management)}</textarea><small>O texto fica salvo neste navegador para o mês selecionado e entra no arquivo gerado.</small></label><article id="monthly-report-preview" class="monthly-report-preview">${reportBody(data,management)}</article></section>`;
}
function reportDocument(data,management,print=false){return `<!doctype html><html><head><meta charset="utf-8"><title>Resumo de Manutenção · ${esc(data.month)}/${esc(data.year)}</title><style>@page{size:A4;margin:16mm}body{font:11pt Calibri,Arial;color:#222;line-height:1.35;max-width:185mm;margin:auto}h1{font-size:17pt;color:#172d42}h3{font-size:12pt;margin:18px 0 5px;border-bottom:1px solid #999;padding-bottom:4px;break-after:avoid}li{margin:4px 0;break-inside:avoid}hr{border:0;border-top:1px solid #aaa}.management-copy{white-space:pre-wrap}${print?'':' '}</style></head><body>${reportBody(data,management)}</body></html>`}
function downloadMonthlyReport(){const data=monthlyReportData(),management=$('#management-text')?.value||'',blob=new Blob(['\ufeff',reportDocument(data,management)],{type:'application/msword;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Resumo_Manutencao_${data.month}_${data.year}.doc`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function printMonthlyReport(){const data=monthlyReportData(),management=$('#management-text')?.value||'',win=window.open('','_blank','noopener,noreferrer');if(!win){alert('Permita a abertura da janela para gerar o PDF.');return}win.document.open();win.document.write(reportDocument(data,management,true));win.document.close();win.onload=()=>{win.focus();win.print()}}
async function copyMonthlyReport(){const data=monthlyReportData(),management=$('#management-text')?.value||'';await navigator.clipboard.writeText(reportBody(data,management,true));const button=$('#copy-monthly-report');if(button){button.textContent='Copiado';setTimeout(()=>button.textContent='Copiar para e-mail',1600)}}
function renderContent(){if(page===3&&!canMonthlyReport()){navigatePage(0);return}$('#title').textContent=pages[page]+' · '+filters.year;$('#content').innerHTML=[periodic,nonperiodic,backlog,monthlyReport][page]();$('#method').innerHTML=page===3?'<p>O resumo mensal usa as mesmas bases e regras dos indicadores da tela. O campo Gestão é editável e salvo somente neste navegador. O arquivo Word e a versão para PDF usam os valores do ano e mês selecionados.</p>':'<p>Fonte: arquivo principal de manutenção, abas Base dados e Base dados_N Periodicas. O site usa a fotografia publicada da base atualizada.</p><ul><li>Periódicas: consecução = linhas executadas ÷ linhas planejadas; não executadas = ordens distintas não executadas ÷ linhas planejadas; pendentes = 1 − consecução − não executadas.</li><li>Não periódicas: contagem distinta de ordem.</li><li>Backlog: idade calculada entre a data original e a atualização da base.</li><li>Os filtros e totais respeitam o ano selecionado.</li></ul>';document.querySelectorAll('[data-pending-areas]').forEach(node=>node.onclick=e=>{e.stopPropagation();showPendingAreas=!showPendingAreas;renderContent();});if($('#export-excel'))$('#export-excel').onclick=()=>window.exportOrdersXlsx(byFilter(D.periodic),filters);if($('#prev'))$('#prev').onclick=()=>{tablePage--;renderContent();};if($('#next'))$('#next').onclick=()=>{tablePage++;renderContent();};if($('#management-text'))$('#management-text').oninput=e=>{try{localStorage.setItem(reportKey(),e.target.value)}catch{}const preview=$('#monthly-report-preview');if(preview)preview.innerHTML=reportBody(monthlyReportData(),e.target.value)};if($('#download-monthly-report'))$('#download-monthly-report').onclick=downloadMonthlyReport;if($('#print-monthly-report'))$('#print-monthly-report').onclick=printMonthlyReport;if($('#copy-monthly-report'))$('#copy-monthly-report').onclick=()=>copyMonthlyReport().catch(()=>alert('Não foi possível copiar automaticamente. Use o arquivo Word.'));}
function navigatePage(i){if(i===3&&!canMonthlyReport())i=0;page=i;filters={year:defaultYear};if(page===3){const available=groups(D.periodic.filter(r=>rowValue(r,'year')===defaultYear),'month');filters.month=available.at(-1)||''}tablePage=0;showPendingAreas=false;const items=pages.map((p,j)=>`<button class="${i===j?'active':''}" aria-current="${i===j?'page':'false'}" data-page="${j}">${p}</button>`);$('#tabs').innerHTML=items.join('');buildFilters();renderContent();}
$('#tabs').onclick=e=>{if(e.target.dataset.page!==undefined)navigatePage(Number(e.target.dataset.page));};
$('#reload').onclick=()=>location.reload();
document.addEventListener('click',e=>{const pending=e.target.closest('[data-pending-areas]');if(pending){showPendingAreas=!showPendingAreas;renderContent();return;}const t=e.target.closest('[data-filter]');if(t){filters[t.dataset.filter]=t.dataset.value;tablePage=0;buildFilters();renderContent();}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-filter],[data-pending-areas]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
document.addEventListener('mousemove',e=>{const t=e.target.closest('[data-tip]'),tip=$('#tooltip');if(t){tip.textContent=t.dataset.tip;tip.hidden=false;tip.style.left=Math.max(8,Math.min(e.clientX+14,window.innerWidth-330))+'px';tip.style.top=Math.max(8,Math.min(e.clientY+14,window.innerHeight-90))+'px';}else tip.hidden=true;});
$('#updated').textContent='Dados extraídos em '+new Date(D.generated).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});navigatePage(Math.min(pages.length-1,Math.max(0,Number(new URLSearchParams(location.search).get('pagina')||0))));
new MutationObserver(()=>{const next=visiblePages();if(next.length!==pages.length){pages=next;navigatePage(Math.min(page,pages.length-1))}}).observe(document.body,{childList:true});
