'use strict';
const D=window.SIMEC_DATA||{periodic:[],nonperiodic:[],assets:[]};
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nf=v=>Number(v||0).toLocaleString('pt-BR'),sourceDate=new Date(D.generated||Date.now());
const CORE=['02AR','03RP','04RS','04SC'],CORE_LABEL={'02AR':'Ordem criada','03RP':'Liberada para planejamento','04RS':'Liberada para programação','04SC':'Ordem programada'};
const assetMap=new Map((D.assets||[]).map(a=>[String(a.code||'').trim().toUpperCase(),a]));
const areaCounts={};(D.periodic||[]).forEach(r=>{if(!r.specialty||!r.area)return;(areaCounts[r.specialty]??={})[r.area]=((areaCounts[r.specialty]||{})[r.area]||0)+1;});
const areaMap=Object.fromEntries(Object.entries(areaCounts).map(([k,v])=>[k,Object.entries(v).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Outros']));
const parseDate=value=>{if(!value)return null;if(Number.isFinite(Number(value))&&Number(value)>1000)return new Date(Date.UTC(1899,11,30)+Number(value)*86400000);const d=new Date(String(value).slice(0,10)+'T00:00:00');return Number.isNaN(d.valueOf())?null:d;};
const dateText=value=>{const d=parseDate(value);return d?d.toLocaleDateString('pt-BR'):'—';};
const ageDays=value=>{const d=parseDate(value);return d?Math.max(0,Math.floor((sourceDate-d)/86400000)):0;};
const inferredArea=r=>r.area||areaMap[r.specialty]||String(r.specialty||'Outros').split(' - ')[0]||'Outros';
const assetCode=r=>{const candidates=[r.description,r.asset,r.service];return String(candidates.find(v=>assetMap.has(String(v||'').trim().toUpperCase()))||r.asset||r.description||'Não informado').trim();};
const assetInfo=code=>assetMap.get(String(code||'').trim().toUpperCase())||{};
const buildOrder=(r,classification)=>{const code=assetCode(r),asset=assetInfo(code),area=inferredArea(r);return{
  id:String(r.id),classification,nature:classification==='Periódica'?'Plano de manutenção':String(r.type||'').toUpperCase()==='PROGRAMADA'?'Corretiva programada':'Corretiva emergencial',
  plan:classification==='Periódica'?(r.plan||'—'):(r.specialty||r.plan||'—'),area,assetCode:code,assetName:asset.name||r.description||r.asset||'Não informado',family:asset.family||'',costCenter:asset.costCenter||'',workCenter:asset.workCenter||'',
  specialty:r.specialty||'Não informado',description:r.description||r.assetName||r.service||'Não informada',service:r.service||'—',period:classification==='Periódica'?(r.period||'—'):'Não periódica',status:r.status||'',system:r.system||'',date:r.date,age:ageDays(r.date),month:r.month||'',
};};
const BACKLOG=[...(D.periodic||[]).filter(r=>r.status==='Pendente').map(r=>buildOrder(r,'Periódica')),...(D.nonperiodic||[]).filter(r=>r.status==='Pendente').map(r=>buildOrder(r,'Não periódica'))];
let filters={},page=0;const PAGE_SIZE=100;
const storage=(prefix,id,value)=>{const key='simec-backlog-'+prefix+'-'+id;if(value===undefined)return localStorage.getItem(key)||'';value?localStorage.setItem(key,value):localStorage.removeItem(key);return value;};
const stage=r=>storage('stage',r.id)||((['02AR','03RP','04RS','04SC'].includes(storage('tag',r.id)))?storage('tag',r.id):'');
const flag=(r,name)=>storage(name.toLowerCase(),r.id)==='1';
const week=r=>storage('week',r.id);
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const year=d.getUTCFullYear(),start=new Date(Date.UTC(year,0,1));return{year,week:Math.ceil((((d-start)/86400000)+1)/7)};}
function weekOptions(){const base=new Date(sourceDate),day=base.getDay()||7;base.setDate(base.getDate()-day+1);return Array.from({length:80},(_,i)=>{const d=new Date(base);d.setDate(base.getDate()+i*7);const x=isoWeek(d);return{value:`${x.year}-W${String(x.week).padStart(2,'0')}`,label:`Semana ${String(x.week).padStart(2,'0')} / ${x.year}`};});}
const weekLabel=value=>{const m=String(value||'').match(/^(\d{4})-W(\d{2})$/);return m?`Semana ${m[2]} / ${m[1]}`:'—';};
const distinct=(rows,key)=>[...new Set(rows.map(r=>r[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR',{numeric:true}));
const planningMeta=(r,index=0)=>{const s=(r.specialty||'').toLowerCase();let team='Equipe '+r.area,people=['Responsável a definir'];if(s.includes('pontes')){team='Equipe Pontes Rolantes';people=['Sergio'];}else if(s.includes('refrig')){team='Equipe Refrigeração';people=['Sergio'];}else if(s.includes('fea')||s.includes('lingotamento')||s.includes('forno')){team='Equipe FEA / LC / FP';people=['Ivan','Vinicius'];}return{team,responsible:people[index%people.length],day:['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira'][index%5]};};
function selected(){const q=(filters.search||'').toLocaleLowerCase('pt-BR');return BACKLOG.filter(r=>{
 if(filters.classification&&r.classification!==filters.classification)return false;if(filters.area&&r.area!==filters.area)return false;if(filters.assetCode&&r.assetCode!==filters.assetCode)return false;if(filters.specialty&&r.specialty!==filters.specialty)return false;if(filters.nature&&r.nature!==filters.nature)return false;if(filters.month&&r.month!==filters.month)return false;
 if(filters.age==='0-7'&&r.age>7)return false;if(filters.age==='8-30'&&(r.age<8||r.age>30))return false;if(filters.age==='31-60'&&(r.age<31||r.age>60))return false;if(filters.age==='61+'&&r.age<61)return false;
 if(filters.stage==='none'&&stage(r))return false;if(filters.stage&&filters.stage!=='none'&&stage(r)!==filters.stage)return false;if(filters.extra==='SC'&&!flag(r,'SC'))return false;if(filters.extra==='GP'&&!flag(r,'GP'))return false;if(filters.week==='none'&&week(r))return false;if(filters.week&&filters.week!=='none'&&week(r)!==filters.week)return false;
 return !q||[r.id,r.plan,r.area,r.assetCode,r.assetName,r.specialty,r.description,r.service].join(' ').toLocaleLowerCase('pt-BR').includes(q);
});}
function options(rows,key,current,all='Todos'){return `<option value="">${all}</option>${distinct(rows,key).map(v=>`<option value="${esc(v)}" ${current===v?'selected':''}>${esc(v)}</option>`).join('')}`;}
function renderFilters(){const weeks=weekOptions();$('#filters').innerHTML=`
 <label>Tipo de ordem<select data-filter="classification">${options(BACKLOG,'classification',filters.classification)}</select></label>
 <label>Área<select data-filter="area">${options(BACKLOG,'area',filters.area,'Todas')}</select></label>
 <label>Bem<select data-filter="assetCode">${options(BACKLOG,'assetCode',filters.assetCode,'Todos')}</select></label>
 <label>Especialidade<select data-filter="specialty">${options(BACKLOG,'specialty',filters.specialty,'Todas')}</select></label>
 <label>Natureza<select data-filter="nature">${options(BACKLOG,'nature',filters.nature,'Todas')}</select></label>
 <label>Mês<select data-filter="month">${options(BACKLOG,'month',filters.month,'Todos')}</select></label>
 <label>Idade<select data-filter="age"><option value="">Todas</option><option value="0-7" ${filters.age==='0-7'?'selected':''}>Até 7 dias</option><option value="8-30" ${filters.age==='8-30'?'selected':''}>8 a 30 dias</option><option value="31-60" ${filters.age==='31-60'?'selected':''}>31 a 60 dias</option><option value="61+" ${filters.age==='61+'?'selected':''}>Acima de 60 dias</option></select></label>
 <label>Etapa<select data-filter="stage"><option value="">Todas</option><option value="none" ${filters.stage==='none'?'selected':''}>Sem etapa</option>${CORE.map(c=>`<option value="${c}" ${filters.stage===c?'selected':''}>${c} · ${CORE_LABEL[c]}</option>`).join('')}</select></label>
 <label>Flag complementar<select data-filter="extra"><option value="">Todas</option><option value="SC" ${filters.extra==='SC'?'selected':''}>SC · Solicitação de compra</option><option value="GP" ${filters.extra==='GP'?'selected':''}>GP · Grande parada</option></select></label>
 <label>Semana / ano<select data-filter="week"><option value="">Todas</option><option value="none" ${filters.week==='none'?'selected':''}>Sem programação</option>${weeks.map(w=>`<option value="${w.value}" ${filters.week===w.value?'selected':''}>${w.label}</option>`).join('')}</select></label>
 <label class="search">Buscar ordem, plano, bem ou descrição<input data-filter="search" value="${esc(filters.search||'')}" placeholder="Digite para buscar"></label><button id="clear">Limpar filtros</button>`;
 $('#filters').onchange=e=>{if(!e.target.dataset.filter)return;filters[e.target.dataset.filter]=e.target.value;page=0;render();};
 const search=$('[data-filter="search"]');search.oninput=e=>{filters.search=e.target.value;page=0;render(false);};$('#clear').onclick=()=>{filters={};page=0;render();};
}
function stageButtons(r){const current=stage(r),index=CORE.indexOf(current),next=CORE[index+1];return `<div class="stage-control"><div class="stage-buttons">${CORE.map((code,i)=>`<button type="button" class="stage-button ${i<=index?'done':''} ${i===index+1?'next':''} ${i>index+1?'locked':''}" data-stage="${code}" data-order="${r.id}" title="${CORE_LABEL[code]}" aria-label="${code} · ${CORE_LABEL[code]}">${code}</button>`).join('')}</div><span class="stage-current">Atual: <strong>${current||'sem etapa'}</strong>${next?` · Próxima: <strong>${next}</strong>`:' · Fluxo concluído'}</span></div>`;}
function rowHtml(r,index){const current=stage(r),canSchedule=['04RS','04SC'].includes(current),meta=planningMeta(r,index);return `<tr><td>${stageButtons(r)}</td><td><button class="flag-toggle ${flag(r,'SC')?'active':''}" data-extra="SC" data-order="${r.id}">SC</button> <button class="flag-toggle ${flag(r,'GP')?'active':''}" data-extra="GP" data-order="${r.id}">GP</button>${r.classification==='Periódica'?'<span class="fixed-badge">PREV</span>':''}</td><td><select class="week-select" data-week data-order="${r.id}" ${canSchedule?'':'disabled title="A semana fica disponível em 04RS ou 04SC"'}><option value="">—</option>${weekOptions().map(w=>`<option value="${w.value}" ${week(r)===w.value?'selected':''}>${w.label}</option>`).join('')}</select></td><td><span class="type-badge ${r.classification==='Não periódica'?'nonperiodic':''}">${esc(r.classification)}</span></td><td>${esc(r.nature)}</td><td><strong>${esc(r.id)}</strong></td><td>${esc(r.plan)}</td><td>${esc(r.area)}</td><td>${esc(r.assetCode)}</td><td class="description">${esc(r.assetName)}</td><td>${esc(r.family||'—')}</td><td>${esc(r.costCenter||'—')}</td><td>${esc(r.specialty)}</td><td class="description">${esc(r.description)}</td><td class="description">${esc(r.service)}</td><td>${esc(r.period)}</td><td>${esc(r.system||r.status)}</td><td>${dateText(r.date)}</td><td class="${r.age>60?'age-high':''}">${nf(r.age)} dias</td><td>${esc(r.month)}</td><td>${esc(meta.team)}</td><td>${esc(meta.responsible)}</td></tr>`;}
function renderKpis(rows){const avg=rows.length?rows.reduce((s,r)=>s+r.age,0)/rows.length:0,assets=new Set(rows.map(r=>r.assetCode)).size;$('#kpis').innerHTML=[['Ordens pendentes',nf(rows.length)],['Planos periódicos',nf(rows.filter(r=>r.classification==='Periódica').length)],['Corretivas pendentes',nf(rows.filter(r=>r.classification==='Não periódica').length)],['Idade média',avg.toLocaleString('pt-BR',{maximumFractionDigits:1})+' dias'],['Bens relacionados',nf(assets)]].map(([a,b])=>`<div class="backlog-kpi"><span>${a}</span><strong>${b}</strong></div>`).join('');}
function summary(title,pairs,color){const max=Math.max(1,...pairs.map(x=>x[1]));return `<div class="summary-panel"><h2>${title}</h2>${pairs.slice(0,12).map(([label,value])=>`<div class="summary-row"><span>${esc(label)}</span><div class="summary-track"><i style="width:${100*value/max}%;background:${color}"></i></div><span class="summary-value">${typeof value==='number'&&!Number.isInteger(value)?value.toLocaleString('pt-BR',{maximumFractionDigits:1}):nf(value)}</span></div>`).join('')||'<div class="empty">Sem dados para a seleção.</div>'}</div>`;}
function renderSummaries(rows){const area=distinct(rows,'area').map(a=>[a,rows.filter(r=>r.area===a).length]).sort((a,b)=>b[1]-a[1]);const stages=['Sem etapa',...CORE].map(code=>{const group=rows.filter(r=>code==='Sem etapa'?!stage(r):stage(r)===code);return[code,group.length?group.reduce((s,r)=>s+r.age,0)/group.length:0];});$('#summaries').innerHTML=summary('Quantidade de ordens por área',area,'#6c2aa6')+summary('Idade média por etapa',stages,'#e5651a');}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3500);}
function render(refreshFilters=true){const rows=selected(),start=page*PAGE_SIZE,visible=rows.slice(start,start+PAGE_SIZE);if(refreshFilters)renderFilters();renderKpis(rows);$('#count').textContent=nf(rows.length)+' ordens pendentes';$('#selection-summary').textContent=nf(rows.length)+' ordens na seleção atual';$('#table-head').innerHTML='<tr><th>Etapa da ordem</th><th>Flags</th><th>Semana / ano</th><th>Tipo</th><th>Natureza</th><th>Ordem</th><th>Plano</th><th>Área</th><th>Bem</th><th>Nome do bem</th><th>Família</th><th>Centro de custo</th><th>Especialidade</th><th>Descrição</th><th>Serviço / manutenção</th><th>Periodicidade</th><th>Status original</th><th>Data original</th><th>Idade</th><th>Mês</th><th>Equipe</th><th>Responsável</th></tr>';$('#table-body').innerHTML=visible.map((r,i)=>rowHtml(r,start+i)).join('')||'<tr><td colspan="22" class="empty">Nenhuma ordem encontrada.</td></tr>';$('#page-info').textContent=`${rows.length?start+1:0}–${Math.min(start+PAGE_SIZE,rows.length)} de ${nf(rows.length)} ordens`;$('#prev').disabled=page===0;$('#next').disabled=start+PAGE_SIZE>=rows.length;renderSummaries(rows);}
$('#table-body').onclick=e=>{const stageButton=e.target.closest('[data-stage]'),extraButton=e.target.closest('[data-extra]');if(stageButton){const r=BACKLOG.find(x=>x.id===stageButton.dataset.order),current=CORE.indexOf(stage(r)),target=CORE.indexOf(stageButton.dataset.stage);if(!r)return;if(target>current+1){const required=CORE[current+1];toast(`Etapa bloqueada. Marque primeiro ${required} · ${CORE_LABEL[required]}.`);return;}if(target===current){toast(`${stageButton.dataset.stage} já é a etapa atual desta ordem.`);return;}storage('stage',r.id,stageButton.dataset.stage);if(!['04RS','04SC'].includes(stageButton.dataset.stage))storage('week',r.id,'');const next=CORE[target+1];render(false);toast(next?`${stageButton.dataset.stage} registrada. Agora avance para ${next}.`:`${stageButton.dataset.stage} registrada. Fluxo concluído.`);return;}if(extraButton){const r=BACKLOG.find(x=>x.id===extraButton.dataset.order),name=extraButton.dataset.extra;if(!r)return;storage(name.toLowerCase(),r.id,flag(r,name)?'':'1');render(false);}};
$('#table-body').onchange=e=>{const select=e.target.closest('[data-week]');if(!select)return;storage('week',select.dataset.order,select.value);render(false);};
function exportRows(){return selected().map((r,i)=>{const meta=planningMeta(r,i);return{...r,stage:stage(r),stageDescription:CORE_LABEL[stage(r)]||'',flagSC:flag(r,'SC')?'SIM':'',flagGP:flag(r,'GP')?'SIM':'',scheduledWeek:weekLabel(week(r)),team:meta.team,responsible:meta.responsible,day:meta.day};});}
const EXPORT_COLUMNS=[['classification','Tipo'],['nature','Natureza'],['id','Ordem'],['plan','Plano'],['area','Área'],['assetCode','Bem'],['assetName','Nome do Bem'],['family','Família'],['costCenter','Centro de Custo'],['workCenter','Centro de Trabalho'],['specialty','Especialidade'],['description','Descrição da Ordem'],['service','Serviço / Manutenção'],['period','Periodicidade'],['system','Status Original'],[r=>dateText(r.date),'Data Original'],['age','Idade (Dias)'],['month','Mês'],['stage','Etapa'],['stageDescription','Descrição da Etapa'],['flagSC','Flag SC'],['flagGP','Flag GP'],['scheduledWeek','Semana / Ano'],['team','Equipe'],['responsible','Responsável'],['day','Dia']].map(([value,label])=>({value,label}));
$('#export-backlog').onclick=()=>window.exportTableXlsx(exportRows(),EXPORT_COLUMNS,'Backlog_Programacao','SIMEC-Backlog-Programacao-'+new Date().toISOString().slice(0,10)+'.xlsx');$('#print-backlog').onclick=()=>window.print();$('#prev').onclick=()=>{page--;render(false);};$('#next').onclick=()=>{page++;render(false);};$('#reload').onclick=()=>location.reload();$('#updated').textContent='Dados extraídos em '+sourceDate.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});render();
