'use strict';

const D=window.SIMEC_DATA||{periodic:[],nonperiodic:[],assets:[]};
const PEOPLE=(window.SIMEC_PEOPLE||[]).filter(p=>p&&p.id&&p.name&&!/openpyxl|arrayformula\s+object/i.test(String(p.name))).sort((a,b)=>String(a.name).localeCompare(String(b.name),'pt-BR'));
const ACCESS=window.SIMEC_ACCESS||{isAdmin:()=>false,canProgram:()=>false,currentId:()=>'',currentName:()=>sessionStorage.getItem('simec_portal_nome_v1')||'Funcionário',roleFor:()=>'leitor'};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fold=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const MAINTENANCE_PEOPLE=PEOPLE.filter(p=>fold(p.type).includes('manutencao'));
const nf=v=>Number(v||0).toLocaleString('pt-BR');
const sourceDate=new Date(D.generated||Date.now());
const CORE=['02AR','03RP','04RS','04SC'];
const CORE_LABEL={'02AR':'Ordem criada','03RP':'Liberada para planejamento','04RS':'Liberada para programação','04SC':'Ordem programada'};
const FLAG_LABEL={SC:'Solicitação de compra',GP:'Grande parada',PREV:'Plano de manutenção preventiva','05RS':'Ordem em reprogramação','AG-CAD':'Aguardando cadastramento de item'};
const WEEKDAYS=['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado','Domingo'];
const personMap=new Map(PEOPLE.map(p=>[String(p.id),p]));
const planningMap=new Map((D.planning||[]).map(p=>[String(p.id),p]));
const assetMap=new Map((D.assets||[]).map(a=>[String(a.code||'').trim().toUpperCase(),a]));
const areaCounts={};
(D.periodic||[]).forEach(r=>{if(!r.specialty||!r.area)return;(areaCounts[r.specialty]??={})[r.area]=((areaCounts[r.specialty]||{})[r.area]||0)+1;});
const areaMap=Object.fromEntries(Object.entries(areaCounts).map(([k,v])=>[k,Object.entries(v).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Outros']));

const parseDate=value=>{if(!value)return null;if(Number.isFinite(Number(value))&&Number(value)>1000)return new Date(Date.UTC(1899,11,30)+Number(value)*86400000);const d=new Date(String(value).slice(0,10)+'T00:00:00');return Number.isNaN(d.valueOf())?null:d;};
const dateText=value=>{const d=parseDate(value);return d?d.toLocaleDateString('pt-BR'):'—';};
const ageDays=value=>{const d=parseDate(value);return d?Math.max(0,Math.floor((sourceDate-d)/86400000)):0;};
const inferredArea=r=>r.area||areaMap[r.specialty]||String(r.specialty||'Outros').split(' - ')[0]||'Outros';
const assetCode=r=>{const candidates=[r.description,r.asset,r.service];return String(candidates.find(v=>assetMap.has(String(v||'').trim().toUpperCase()))||r.asset||r.description||'Não informado').trim();};
const assetInfo=code=>assetMap.get(String(code||'').trim().toUpperCase())||{};
const buildOrder=(r,classification)=>{const code=assetCode(r),asset=assetInfo(code),area=inferredArea(r);return{
  id:String(r.id),classification,nature:classification==='Periódica'?'Plano de manutenção':String(r.type||'').toUpperCase()==='PROGRAMADA'?'Corretiva programada':'Corretiva emergencial',
  plan:classification==='Periódica'?(r.plan||'—'):(r.specialty||r.plan||'—'),area,assetCode:code,assetName:asset.name||r.description||r.asset||'Não informado',family:asset.family||'',costCenter:asset.costCenter||'',workCenter:asset.workCenter||'',
  specialty:r.specialty||'Não informado',description:r.description||r.assetName||r.service||'Não informada',service:r.service||'—',period:classification==='Periódica'?(r.period||'—'):'Não periódica',status:r.status||'',system:r.system||'',executors:r.executors||'',date:r.date,age:ageDays(r.date),month:r.month||'',
};};
const ALL_ORDERS=[...(D.periodic||[]).map(r=>buildOrder(r,'Periódica')),...(D.nonperiodic||[]).map(r=>buildOrder(r,'Não periódica'))];
const ORDER_MAP=new Map(ALL_ORDERS.map(r=>[r.id,r]));
const BACKLOG=ALL_ORDERS.filter(r=>r.status==='Pendente');
let filters={},pointFilters={},page=0,activeView='programacao',calendarWeek='',calendarArea='';
const dirtyOrders=new Set();
const PAGE_SIZE=100;

const seedValue=(prefix,id)=>{const p=planningMap.get(String(id))||{};if(prefix==='stage')return p.stage||'';if(prefix==='sc')return fold(p.flagSC)==='sim'?'1':'';if(prefix==='gp')return fold(p.flagGP)==='sim'?'1':'';if(prefix==='05rs')return fold(p.flag05RS)==='sim'?'1':'';if(prefix==='ag-cad')return fold(p.flagAGCAD)==='sim'?'1':'';if(prefix==='week'){const m=String(p.scheduledWeek||'').match(/Semana\s+(\d+)\s*\/\s*(\d{4})/i);return m?`${m[2]}-W${String(m[1]).padStart(2,'0')}`:'';}if(prefix==='day')return p.scheduledDay||'';if(prefix==='hours')return p.plannedHours||'';return '';};
const storage=(prefix,id,value)=>{const key='simec-backlog-'+prefix+'-'+id;if(value===undefined){const local=localStorage.getItem(key);return local===null?seedValue(prefix,id):local;}value?localStorage.setItem(key,value):localStorage.removeItem(key);return value;};
const jsonStorage=(prefix,id,value)=>{const key='simec-backlog-'+prefix+'-'+id;if(value===undefined){try{const local=localStorage.getItem(key);if(local!==null)return JSON.parse(local||'[]');const p=planningMap.get(String(id))||{};if(prefix==='labor')return String(p.laborIds||'').split(/\s*\|\s*|\s*,\s*/).filter(Boolean);if(prefix==='history'&&p.modifiedBy)return[{by:p.modifiedBy,userId:p.modifiedUser||'',at:p.modifiedAt||'',action:p.modifiedAction||'Alteração importada'}];return[];}catch{return[]}}if(value&&value.length)localStorage.setItem(key,JSON.stringify(value));else localStorage.removeItem(key);return value;};
const stage=r=>storage('stage',r.id)||((CORE.includes(storage('tag',r.id)))?storage('tag',r.id):'');
const flag=(r,name)=>storage(name.toLowerCase(),r.id)==='1';
const week=r=>storage('week',r.id);
const day=r=>storage('day',r.id);
const hours=r=>Number(storage('hours',r.id)||0);
const assignments=r=>{const saved=jsonStorage('assignments',r.id);if(Array.isArray(saved)&&saved.length)return saved.map(a=>({...a,id:String(a.id),hours:Number(a.hours)||0})).filter(a=>personMap.has(a.id)||a.thirdParty);const p=planningMap.get(String(r.id))||{},hoursById=new Map();String(p.laborHours||'').split(/\s*\|\s*/).forEach(item=>{const match=item.match(/\((\d+)\)\s*:\s*([\d,.]+)h/i);if(match)hoursById.set(match[1],Number(match[2].replace(',','.'))||0);});const legacy=jsonStorage('labor',r.id).map(String).filter(id=>personMap.has(id));return legacy.map(id=>({id,hours:hoursById.get(id)||hours(r)}));};
const saveAssignments=(r,value)=>{jsonStorage('assignments',r.id,value);jsonStorage('labor',r.id,value.map(a=>String(a.id)));return value;};
const assignedIds=r=>assignments(r).map(a=>a.id);
const assignmentHours=(r,id)=>assignments(r).find(a=>a.id===String(id))?.hours||0;
const totalOrderHours=r=>assignments(r).reduce((sum,a)=>sum+a.hours,0)||hours(r);
const personName=id=>personMap.get(String(id))?.name||String(id);
const allocationName=a=>a?.thirdParty?(a.name||'Terceiro'):personName(a?.id);
const allocationCode=a=>a?.thirdParty?(a.registration||a.company||'TERCEIRO'):String(a?.id||'');
const thirdPartyId=(name,company,registration)=>'TERC-'+fold(`${registration}-${company}-${name}`).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const isPointed=r=>{const value=fold(`${r.status} ${r.system}`);return value.includes('executada')||value.includes('encerrad');};
const currentUser=()=>({name:ACCESS.currentName()||window.SIMEC_AUTH?.name||'Funcionário',id:ACCESS.currentId()||window.SIMEC_AUTH?.userId||''});
const audit=r=>{try{const local=localStorage.getItem('simec-backlog-audit-'+r.id);if(local)return JSON.parse(local);const p=planningMap.get(String(r.id))||{};return p.modifiedBy?{by:p.modifiedBy,userId:p.modifiedUser||'',at:p.modifiedAt||'',action:p.modifiedAction||'Alteração importada'}:null}catch{return null}};
function markDirty(r){dirtyOrders.add(r.id);}
function saveAudit(r,action='Tags e programação salvas'){
 const user=currentUser(),entry={by:user.name,userId:user.id,at:new Date().toISOString(),action,stage:stage(r),flagSC:flag(r,'SC'),flagGP:flag(r,'GP'),flag05RS:flag(r,'05RS'),flagAGCAD:flag(r,'AG-CAD'),week:week(r),day:day(r),hours:totalOrderHours(r),labor:assignments(r)};
 localStorage.setItem('simec-backlog-audit-'+r.id,JSON.stringify(entry));
 const history=jsonStorage('history',r.id);history.unshift(entry);jsonStorage('history',r.id,history.slice(0,30));dirtyOrders.delete(r.id);return entry;
}
function auditHtml(r){if(dirtyOrders.has(r.id))return '<div class="audit-info pending">Alteração não salva</div>';const info=audit(r);if(!info)return '<div class="audit-info"><span>Ainda não salva</span></div>';const when=new Date(info.at);return `<div class="audit-info"><strong>${esc(info.by||'Funcionário')}</strong>${info.userId?`<span>Matrícula ${esc(info.userId)}</span>`:''}<span>${esc(info.action||'Alteração salva')}</span><span>${Number.isNaN(when.valueOf())?'':when.toLocaleString('pt-BR')}</span></div>`;}

function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())),dow=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-dow);const year=d.getUTCFullYear(),start=new Date(Date.UTC(year,0,1));return{year,week:Math.ceil((((d-start)/86400000)+1)/7)};}
function weekOptions(){const base=new Date(sourceDate),dow=base.getDay()||7;base.setDate(base.getDate()-dow+1);return Array.from({length:80},(_,i)=>{const d=new Date(base);d.setDate(base.getDate()+i*7);const x=isoWeek(d);return{value:`${x.year}-W${String(x.week).padStart(2,'0')}`,label:`Semana ${String(x.week).padStart(2,'0')} / ${x.year}`};});}
const weekLabel=value=>{const m=String(value||'').match(/^(\d{4})-W(\d{2})$/);return m?`Semana ${m[2]} / ${m[1]}`:'—';};
const distinct=(rows,key)=>[...new Set(rows.map(r=>r[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'pt-BR',{numeric:true}));
const planningMeta=r=>({team:'Equipe '+r.area});

function recommendedPeople(r){const text=fold(`${r.area} ${r.specialty} ${r.description} ${r.service}`);let match;
 if(text.includes('pontes rolantes')||text.includes('ponte rolante'))match=p=>{const a=fold(p.area);return a.includes('pontes rolantes')&&(text.includes('eletric')?a.includes('eletric'):a.includes('mecan'));};
 else if(text.includes('refriger'))match=p=>fold(p.area).includes('refriger');
 else if(text.includes('despoeir')||text.includes('dcs')||text.includes('rmh'))match=p=>fold(p.area).includes('despoeir');
 else if(text.includes('eletric'))match=p=>fold(p.area).includes('manutencao eletrica');
 else if(text.includes('mecan')||text.includes('hidraul')||text.includes('lubr'))match=p=>fold(p.area).includes('manutencao mecanica');
 else match=p=>fold(p.type).includes('manutencao');
 const preferred=MAINTENANCE_PEOPLE.filter(match);return preferred.length?preferred:MAINTENANCE_PEOPLE;
}
function dailyLoad(personId,targetWeek,targetDay,excludeOrder=''){if(!personId||!targetWeek||!targetDay)return 0;return ALL_ORDERS.reduce((sum,r)=>sum+(r.id!==excludeOrder&&week(r)===targetWeek&&day(r)===targetDay?assignmentHours(r,personId):0),0);}
function remainingHours(personId,r){return Math.max(0,8-dailyLoad(personId,week(r),day(r),r.id)-assignmentHours(r,personId));}
function scheduleReady(r){return CORE.indexOf(stage(r))>=2&&week(r)&&day(r)&&hours(r)>0;}
function scheduleIsValid(r,next={}){const targetWeek=next.week??week(r),targetDay=next.day??day(r),defaultHours=Number(next.hours??hours(r));if(defaultHours<0||defaultHours>8)return{ok:false,message:'As horas devem ficar entre 0 e 8.'};if(!targetWeek||!targetDay)return{ok:true};for(const allocation of assignments(r)){const allocationValue=next.assignmentId===allocation.id?Number(next.assignmentHours):allocation.hours;if(allocationValue<=0||allocationValue>8)return{ok:false,message:`Informe entre 0,5 e 8 horas para ${personName(allocation.id)}.`};const total=dailyLoad(allocation.id,targetWeek,targetDay,r.id)+allocationValue;if(total>8)return{ok:false,message:`${personName(allocation.id)} ficaria com ${total.toLocaleString('pt-BR')} horas em ${targetDay}. O limite é 8 horas.`};}return{ok:true};}
function peopleOptions(r){const preferred=recommendedPeople(r),preferredIds=new Set(preferred.map(p=>String(p.id))),others=MAINTENANCE_PEOPLE.filter(p=>!preferredIds.has(String(p.id))),option=p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.area)}${week(r)&&day(r)?` · ${remainingHours(p.id,r).toLocaleString('pt-BR')}h livres`:''}</option>`;return `<option value="">Selecione um profissional</option><optgroup label="Manutenção · especialidade da ordem">${preferred.map(option).join('')}</optgroup><optgroup label="Outros profissionais da manutenção">${others.map(option).join('')}</optgroup><optgroup label="Serviço externo"><option value="__third_party__">Obra de terceiro…</option></optgroup>`;}
function firstName(id){return String(personName(id)).trim().split(/\s+/)[0]||String(id);}
function assignmentChips(r){return assignments(r).map(a=>`<span class="labor-chip ${a.thirdParty?'third-party':''}"><b>${esc(a.thirdParty?allocationName(a):firstName(a.id))}</b><small>${esc(allocationCode(a))}${a.thirdParty&&a.company?` · ${esc(a.company)}`:''}</small><input type="number" min="0.5" max="8" step="0.5" value="${a.hours||''}" data-assignment-hours data-person="${esc(a.id)}" data-order="${esc(r.id)}" aria-label="Horas de ${esc(allocationName(a))}"><em>h</em><button type="button" data-remove-labor="${esc(a.id)}" data-order="${esc(r.id)}" aria-label="Remover ${esc(allocationName(a))}">×</button></span>`).join('')||'<span class="no-labor">Ninguém definido</span>';}

function selected(){const q=(filters.search||'').toLocaleLowerCase('pt-BR');return BACKLOG.filter(r=>{
 if(filters.classification&&r.classification!==filters.classification)return false;if(filters.area&&r.area!==filters.area)return false;if(filters.assetCode&&r.assetCode!==filters.assetCode)return false;if(filters.specialty&&r.specialty!==filters.specialty)return false;if(filters.nature&&r.nature!==filters.nature)return false;if(filters.month&&r.month!==filters.month)return false;
 if(filters.age==='0-7'&&r.age>7)return false;if(filters.age==='8-30'&&(r.age<8||r.age>30))return false;if(filters.age==='31-60'&&(r.age<31||r.age>60))return false;if(filters.age==='61+'&&r.age<61)return false;
 if(filters.stage==='none'&&stage(r))return false;if(filters.stage&&filters.stage!=='none'&&stage(r)!==filters.stage)return false;if(filters.extra&&!flag(r,filters.extra))return false;if(filters.week==='none'&&week(r))return false;if(filters.week&&filters.week!=='none'&&week(r)!==filters.week)return false;if(filters.labor&& !assignedIds(r).includes(filters.labor))return false;
 return !q||[r.id,r.plan,r.area,r.assetCode,r.assetName,r.specialty,r.description,r.service].join(' ').toLocaleLowerCase('pt-BR').includes(q);
});}
function options(rows,key,current,all='Todos'){return `<option value="">${all}</option>${distinct(rows,key).map(v=>`<option value="${esc(v)}" ${current===v?'selected':''}>${esc(v)}</option>`).join('')}`;}
function renderFilters(){const weeks=weekOptions();$('#filters').innerHTML=`
 <label>Tipo de ordem<select data-filter="classification">${options(BACKLOG,'classification',filters.classification)}</select></label>
 <label>Área<select data-filter="area">${options(BACKLOG,'area',filters.area,'Todas')}</select></label>
 <label>Bem<select data-filter="assetCode">${options(BACKLOG,'assetCode',filters.assetCode,'Todos')}</select></label>
 <label>Especialidade<select data-filter="specialty">${options(BACKLOG,'specialty',filters.specialty,'Todas')}</select></label>
 <label>Natureza<select data-filter="nature">${options(BACKLOG,'nature',filters.nature,'Todas')}</select></label>
 <label>Mês<select data-filter="month">${options(BACKLOG,'month',filters.month,'Todos')}</select></label>
 <label>Idade<select data-filter="age"><option value="">Todas</option><option value="0-7" ${filters.age==='0-7'?'selected':''}>Até 7 dias</option><option value="8-30" ${filters.age==='8-30'?'selected':''}>8 a 30 dias</option><option value="31-60" ${filters.age==='31-60'?'selected':''}>31 a 60 dias</option><option value="61+" ${filters.age==='61+'?'selected':''}>Acima de 60 dias</option></select></label>
 <label>Etapa<select data-filter="stage"><option value="">Todas</option><option value="none" ${filters.stage==='none'?'selected':''}>Sem etapa</option>${CORE.map(c=>`<option value="${c}" ${filters.stage===c?'selected':''}>${c} · ${CORE_LABEL[c]}</option>`).join('')}</select></label>
 <label>Flag complementar<select data-filter="extra"><option value="">Todas</option>${['SC','GP','05RS','AG-CAD'].map(code=>`<option value="${code}" ${filters.extra===code?'selected':''}>${code} · ${FLAG_LABEL[code]}</option>`).join('')}</select></label>
 <label>Semana / ano<select data-filter="week"><option value="">Todas</option><option value="none" ${filters.week==='none'?'selected':''}>Sem programação</option>${weeks.map(w=>`<option value="${w.value}" ${filters.week===w.value?'selected':''}>${w.label}</option>`).join('')}</select></label>
 <label>Mão de obra<select data-filter="labor"><option value="">Todos</option>${PEOPLE.map(p=>`<option value="${esc(p.id)}" ${filters.labor===String(p.id)?'selected':''}>${esc(p.name)} · ${esc(p.area)}</option>`).join('')}</select></label>
 <label class="search">Buscar ordem, plano, bem ou descrição<input data-filter="search" value="${esc(filters.search||'')}" placeholder="Digite para buscar"></label><button id="clear">Limpar filtros</button>`;
 $('#filters').onchange=e=>{if(!e.target.dataset.filter)return;filters[e.target.dataset.filter]=e.target.value;page=0;render();};
 const search=$('[data-filter="search"]');search.oninput=e=>{filters.search=e.target.value;page=0;render(false);};$('#clear').onclick=()=>{filters={};page=0;render();};
}
function stageButtons(r){const current=stage(r),index=CORE.indexOf(current),next=CORE[index+1];return `<div class="stage-control"><div class="stage-buttons">${CORE.map((code,i)=>`<button type="button" class="stage-button ${i<=index?'done':''} ${i===index+1?'next':''} ${i>index+1?'locked':''}" data-stage="${code}" data-order="${r.id}" title="${CORE_LABEL[code]}" aria-label="${code} · ${CORE_LABEL[code]}">${code}</button>`).join('')}</div><span class="stage-current">Atual: <strong>${current||'sem etapa'}</strong>${next?` · Próxima: <strong>${next}</strong>`:' · Fluxo concluído'}</span></div>`;}
function rowHtml(r){const canSchedule=CORE.indexOf(stage(r))>=2,programmed=stage(r)==='04SC',programAction=ACCESS.canProgram()?`<button type="button" class="program-order" data-program data-order="${r.id}" ${canSchedule?'':'disabled'}>${programmed?'Salvar programação':'Concluir e salvar programação'}</button>`:'<span class="no-program-access">Programação restrita</span>';return `<tr class="${dirtyOrders.has(r.id)?'unsaved':''}"><td>${stageButtons(r)}<div class="stage-save">${programAction}</div></td><td><button type="button" title="SC · ${FLAG_LABEL.SC}" aria-label="SC · ${FLAG_LABEL.SC}" class="flag-toggle ${flag(r,'SC')?'active':''}" data-extra="SC" data-order="${r.id}">SC</button> <button type="button" title="GP · ${FLAG_LABEL.GP}" aria-label="GP · ${FLAG_LABEL.GP}" class="flag-toggle ${flag(r,'GP')?'active':''}" data-extra="GP" data-order="${r.id}">GP</button> <button type="button" title="05RS · ${FLAG_LABEL['05RS']}" aria-label="05RS · ${FLAG_LABEL['05RS']}" class="flag-toggle reprogram ${flag(r,'05RS')?'active':''}" data-extra="05RS" data-order="${r.id}">05RS</button> <button type="button" title="AG-CAD · ${FLAG_LABEL['AG-CAD']}" aria-label="AG-CAD · ${FLAG_LABEL['AG-CAD']}" class="flag-toggle waiting ${flag(r,'AG-CAD')?'active':''}" data-extra="AG-CAD" data-order="${r.id}">AG-CAD</button>${r.classification==='Periódica'?`<span class="fixed-badge" title="PREV · ${FLAG_LABEL.PREV}">PREV</span>`:''}</td>
 <td><select class="week-select" data-week data-order="${r.id}" ${canSchedule?'':'disabled title="Disponível em 04RS ou 04SC"'}><option value="">—</option>${weekOptions().map(w=>`<option value="${w.value}" ${week(r)===w.value?'selected':''}>${w.label}</option>`).join('')}</select></td>
 <td><select class="day-select" data-day data-order="${r.id}" ${canSchedule?'':'disabled'}><option value="">—</option>${WEEKDAYS.map(v=>`<option value="${v}" ${day(r)===v?'selected':''}>${v}</option>`).join('')}</select></td>
 <td><input class="hours-input" type="number" min="0.5" max="8" step="0.5" value="${hours(r)||''}" placeholder="0" data-hours data-order="${r.id}" ${canSchedule?'':'disabled'}></td>
 <td><div class="labor-control"><div class="labor-add"><select data-labor-select data-order="${r.id}" ${canSchedule?'':'disabled'}>${peopleOptions(r)}</select><button type="button" data-add-labor data-order="${r.id}" ${canSchedule?'':'disabled'}>Adicionar</button></div><div class="labor-chips">${assignmentChips(r)}</div></div></td><td><div class="order-actions">${programAction}<button type="button" class="save-order" data-save data-order="${r.id}" ${dirtyOrders.has(r.id)?'':'disabled'}>Salvar tags</button>${programmed?'<span class="programmed-badge">04SC concluída</span>':''}</div></td><td class="audit-cell">${auditHtml(r)}</td>
 <td><span class="type-badge ${r.classification==='Não periódica'?'nonperiodic':''}">${esc(r.classification)}</span></td><td class="${r.age>60?'age-high':''}">${nf(r.age)} dias</td><td>${esc(r.nature)}</td><td><strong>${esc(r.id)}</strong></td><td>${esc(r.plan)}</td><td>${esc(r.area)}</td><td>${esc(r.assetCode)}</td><td class="description">${esc(r.assetName)}</td><td>${esc(r.family||'—')}</td><td>${esc(r.costCenter||'—')}</td><td>${esc(r.specialty)}</td><td class="description">${esc(r.description)}</td><td class="description">${esc(r.service)}</td><td>${esc(r.period)}</td><td>${esc(r.system||r.status)}</td><td>${dateText(r.date)}</td><td>${esc(r.month)}</td><td>${esc(planningMeta(r).team)}</td></tr>`;}

function completeSchedule(r){if(!r)return;if(!ACCESS.canProgram()){toast('Somente administrador ou Programador pode programar ordens.');return;}if(!['04RS','04SC'].includes(stage(r))){toast('A ordem precisa estar na etapa 04RS para ser programada.');return;}if(!week(r)||!WEEKDAYS.includes(day(r))){toast('Informe semana e dia antes de programar a ordem.');return;}if(!assignments(r).length){toast('Adicione pelo menos um funcionário com suas horas antes de programar a ordem.');return;}const valid=scheduleIsValid(r);if(!valid.ok){toast(valid.message);return;}storage('stage',r.id,'04SC');markDirty(r);saveAudit(r,'Ordem programada');render(false);downloadSavedWorkbook();toast(`Ordem ${r.id} programada e salva por ${currentUser().name}. Arquivo Excel para exportação gerado. Salvo neste navegador.`);}
function renderKpis(rows){const avg=rows.length?rows.reduce((s,r)=>s+r.age,0)/rows.length:0,assets=new Set(rows.map(r=>r.assetCode)).size,assigned=rows.filter(r=>assignedIds(r).length).length;$('#kpis').innerHTML=[['Ordens pendentes',nf(rows.length)],['Planos periódicos',nf(rows.filter(r=>r.classification==='Periódica').length)],['Corretivas pendentes',nf(rows.filter(r=>r.classification==='Não periódica').length)],['Com mão de obra',nf(assigned)],['Idade média',avg.toLocaleString('pt-BR',{maximumFractionDigits:1})+' dias'],['Bens relacionados',nf(assets)]].map(([a,b])=>`<div class="backlog-kpi"><span>${a}</span><strong>${b}</strong></div>`).join('');}
function summary(title,pairs,color){const max=Math.max(1,...pairs.map(x=>x[1]));return `<div class="summary-panel"><h2>${title}</h2>${pairs.slice(0,12).map(([label,value])=>`<div class="summary-row"><span>${esc(label)}</span><div class="summary-track"><i style="width:${100*value/max}%;background:${color}"></i></div><span class="summary-value">${typeof value==='number'&&!Number.isInteger(value)?value.toLocaleString('pt-BR',{maximumFractionDigits:1}):nf(value)}</span></div>`).join('')||'<div class="empty">Sem dados para a seleção.</div>'}</div>`;}
function renderSummaries(rows){const area=distinct(rows,'area').map(a=>[a,rows.filter(r=>r.area===a).length]).sort((a,b)=>b[1]-a[1]);const stages=['Sem etapa',...CORE].map(code=>{const group=rows.filter(r=>code==='Sem etapa'?!stage(r):stage(r)===code);return[code,group.length?group.reduce((s,r)=>s+r.age,0)/group.length:0];});$('#summaries').innerHTML=summary('Quantidade de ordens por área',area,'#6c2aa6')+summary('Idade média por etapa',stages,'#e5651a');}
function renderCalendar(){const programmed=ALL_ORDERS.filter(r=>week(r)&&day(r)&&assignments(r).length),weeks=[...new Set(programmed.map(week))].sort();if(!calendarWeek)calendarWeek=weeks[0]||weekOptions()[0]?.value||'';const weekValues=[...new Set([...weeks,...weekOptions().slice(0,12).map(w=>w.value)])].sort(),weekSelector=$('#calendar-week');weekSelector.innerHTML=weekValues.map(value=>`<option value="${value}" ${value===calendarWeek?'selected':''}>${weekLabel(value)}</option>`).join('');weekSelector.onchange=()=>{calendarWeek=weekSelector.value;renderCalendar();};const areas=distinct(BACKLOG,'area'),areaSelector=$('#calendar-area');areaSelector.innerHTML=`<option value="">Todas as áreas</option>${areas.map(value=>`<option value="${esc(value)}" ${value===calendarArea?'selected':''}>${esc(value)}</option>`).join('')}`;areaSelector.onchange=()=>{calendarArea=areaSelector.value;renderCalendar();};$('#calendar-clear-area').onclick=()=>{calendarArea='';renderCalendar();};const visible=programmed.filter(r=>week(r)===calendarWeek&&(!calendarArea||r.area===calendarArea));const totalHours=visible.reduce((sum,r)=>sum+assignments(r).reduce((s,a)=>s+a.hours,0),0),peopleCount=new Set(visible.flatMap(r=>assignments(r).map(a=>a.id))).size;$('#print-filter-summary').textContent=`${weekLabel(calendarWeek)} · ${calendarArea||'Todas as áreas'} · ${nf(visible.length)} ordem(ns) · ${nf(peopleCount)} profissional(is) · ${totalHours.toLocaleString('pt-BR')} h`;$('#calendar-board').innerHTML=WEEKDAYS.map(dayName=>{const rows=visible.filter(r=>day(r)===dayName),cards=rows.flatMap(r=>assignments(r).map(a=>`<article class="calendar-order"><strong>OS ${esc(r.id)}</strong><span>${esc(a.thirdParty?allocationName(a):firstName(a.id))} · ${esc(allocationCode(a))}</span><b>${a.hours.toLocaleString('pt-BR')} h</b><small>${esc(r.area)} · ${esc(r.specialty)}</small></article>`)).join('');return `<section class="calendar-day"><header><strong>${esc(dayName.replace('-feira',''))}</strong><span>${nf(rows.length)} ordem(ns)</span></header><div>${cards||'<p class="calendar-empty">Sem ordens programadas</p>'}</div></section>`;}).join('');const detailRows=visible.flatMap(r=>assignments(r).map(a=>({r,a}))).sort((x,y)=>WEEKDAYS.indexOf(day(x.r))-WEEKDAYS.indexOf(day(y.r))||x.r.id.localeCompare(y.r.id,'pt-BR',{numeric:true}));$('#calendar-detail-body').innerHTML=detailRows.map(({r,a})=>`<tr><td>${esc(day(r))}</td><td><strong>${esc(r.id)}</strong></td><td>${esc(r.area)}</td><td>${esc(r.assetCode)} · ${esc(r.assetName)}</td><td>${esc(r.service)}<small>${esc(r.specialty)}</small></td><td>${esc(allocationName(a))}${a.thirdParty&&a.company?`<small>${esc(a.company)}</small>`:''}</td><td>${esc(allocationCode(a))}</td><td><strong>${a.hours.toLocaleString('pt-BR')} h</strong></td></tr>`).join('')||'<tr><td colspan="8" class="empty">Nenhuma programação para a semana e área selecionadas.</td></tr>';}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),4000);}
function render(refreshFilters=true){const rows=selected(),start=page*PAGE_SIZE,visible=rows.slice(start,start+PAGE_SIZE);if(refreshFilters)renderFilters();renderKpis(rows);$('#count').textContent=nf(rows.length)+' ordens pendentes';$('#selection-summary').textContent=nf(rows.length)+' ordens na seleção atual';$('#pending-changes').textContent=dirtyOrders.size?`${nf(dirtyOrders.size)} ordem(ns) com alterações não salvas`:'Todas as alterações estão salvas';$('#save-all').disabled=!dirtyOrders.size;$('#table-head').innerHTML='<tr><th>Etapa da ordem</th><th>Flags</th><th>Semana / ano</th><th>Dia</th><th>Horas para adicionar</th><th>Mão de obra e horas individuais</th><th>Ações</th><th>Última alteração</th><th>Tipo</th><th>Idade</th><th>Natureza</th><th>Ordem</th><th>Plano</th><th>Área</th><th>Bem</th><th>Nome do bem</th><th>Família</th><th>Centro de custo</th><th>Especialidade</th><th>Descrição</th><th>Serviço / manutenção</th><th>Periodicidade</th><th>Status original</th><th>Data original</th><th>Mês</th><th>Equipe</th></tr>';$('#table-body').innerHTML=visible.map(rowHtml).join('')||'<tr><td colspan="26" class="empty">Nenhuma ordem encontrada.</td></tr>';$('#page-info').textContent=`${rows.length?start+1:0}–${Math.min(start+PAGE_SIZE,rows.length)} de ${nf(rows.length)} ordens`;$('#prev').disabled=page===0;$('#next').disabled=start+PAGE_SIZE>=rows.length;renderSummaries(rows);renderCalendar();}

function pointRows(){const rows=[];for(const r of ALL_ORDERS){for(const allocation of assignments(r)){const p=allocation.thirdParty?{name:allocationName(allocation),area:allocation.company||'Obra de terceiro',type:'Terceiro'}:personMap.get(allocation.id);if(!p)continue;rows.push({week:week(r),day:day(r),hours:allocation.hours,personId:allocationCode(allocation),person:p,order:r,pointed:isPointed(r)});}}return rows;}
function filteredPointRows(){return pointRows().filter(x=>(!pointFilters.week||x.week===pointFilters.week)&&(!pointFilters.person||x.personId===pointFilters.person)&&(!pointFilters.status||pointFilters.status===(x.pointed?'pointed':'pending')));}
function renderPointing(){const all=pointRows(),rows=filteredPointRows().sort((a,b)=>`${a.week}|${WEEKDAYS.indexOf(a.day)}|${a.person.name}`.localeCompare(`${b.week}|${WEEKDAYS.indexOf(b.day)}|${b.person.name}`,'pt-BR')),weeks=[...new Set(all.map(x=>x.week).filter(Boolean))].sort(),people=[...new Map(all.map(x=>[x.personId,x.person])).values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));
 $('#apontamento-filters').innerHTML=`<label>Semana<select data-point-filter="week"><option value="">Todas</option>${weeks.map(v=>`<option value="${v}" ${pointFilters.week===v?'selected':''}>${weekLabel(v)}</option>`).join('')}</select></label><label>Funcionário<select data-point-filter="person"><option value="">Todos</option>${people.map(p=>`<option value="${p.id}" ${pointFilters.person===String(p.id)?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>Apontamento<select data-point-filter="status"><option value="">Todos</option><option value="pointed" ${pointFilters.status==='pointed'?'selected':''}>Apontada</option><option value="pending" ${pointFilters.status==='pending'?'selected':''}>Aguardando encerramento</option></select></label><button type="button" id="clear-point-filters">Limpar filtros</button>`;
 $('#apontamento-filters').onchange=e=>{if(!e.target.dataset.pointFilter)return;pointFilters[e.target.dataset.pointFilter]=e.target.value;renderPointing();};$('#clear-point-filters').onclick=()=>{pointFilters={};renderPointing();};
 const totalHours=rows.reduce((s,x)=>s+x.hours,0),pointed=rows.filter(x=>x.pointed).length,peopleCount=new Set(rows.map(x=>x.personId)).size;
 $('#apontamento-kpis').innerHTML=[['Programações',nf(rows.length)],['Apontadas',nf(pointed)],['Aguardando',nf(rows.length-pointed)],['Horas programadas',totalHours.toLocaleString('pt-BR',{maximumFractionDigits:1})+' h'],['Funcionários',nf(peopleCount)]].map(([a,b])=>`<div class="backlog-kpi"><span>${a}</span><strong>${b}</strong></div>`).join('');
 $('#apontamento-body').innerHTML=rows.map(x=>`<tr><td>${weekLabel(x.week)}</td><td>${esc(x.day||'—')}</td><td><strong>${esc(x.person.name)}</strong></td><td>${esc(x.person.id)}</td><td>${esc(x.person.area)}</td><td>${x.hours.toLocaleString('pt-BR')} h</td><td>${esc(x.order.id)}</td><td>${esc(x.order.classification)}</td><td>${esc(x.order.specialty)}</td><td>${esc(x.order.system||x.order.status)}</td><td><span class="point-status ${x.pointed?'pointed':'pending'}">${x.pointed?'Apontada':'Aguardando encerramento'}</span></td><td>${esc(x.order.executors||'—')}</td></tr>`).join('')||'<tr><td colspan="12" class="empty">Nenhuma mão de obra programada para a seleção.</td></tr>';
 const groups=new Map();for(const x of rows){const key=[x.week,x.day,x.personId].join('|'),g=groups.get(key)||{...x,hours:0};g.hours+=x.hours;groups.set(key,g);}$('#capacity-board').innerHTML=[...groups.values()].sort((a,b)=>`${a.week}|${a.day}|${a.person.name}`.localeCompare(`${b.week}|${b.day}|${b.person.name}`,'pt-BR')).map(g=>`<div class="capacity-card"><div><strong>${esc(g.person.name)}</strong><span>${weekLabel(g.week)} · ${esc(g.day||'—')}</span></div><b class="${g.hours>8?'overload':''}">${g.hours.toLocaleString('pt-BR')} / 8 h</b><div class="capacity-track"><i style="width:${Math.min(100,g.hours/8*100)}%"></i></div></div>`).join('')||'<div class="empty">A capacidade aparecerá quando houver programação com mão de obra.</div>';
}
function renderFlowLegend(){const items=[...CORE.map(code=>[code,CORE_LABEL[code]]),...Object.entries(FLAG_LABEL)];$('#flow-tag-legend').innerHTML=items.map(([code,label])=>`<article title="${esc(code)} · ${esc(label)}"><strong>${esc(code)}</strong><span>${esc(label)}</span></article>`).join('');}
function setView(view){activeView=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#programacao-view').hidden=view!=='programacao';$('#calendario-view').hidden=view!=='calendario';$('#apontamentos-view').hidden=view!=='apontamentos';$('#fluxo-view').hidden=view!=='fluxo';if(view==='apontamentos'){renderPointing();$('#count').textContent=nf(pointRows().length)+' alocações';}else if(view==='fluxo'){renderFlowLegend();$('#count').textContent='Consulta do processo';}else if(view==='calendario'){renderCalendar();$('#count').textContent='Programação semanal completa';}else{filters={};page=0;render(true);}}

let thirdPartyOrder='';
function openThirdPartyDialog(r){
 if(!scheduleReady(r)){toast('Informe semana, dia e as horas do terceiro antes de adicioná-lo.');return;}
 thirdPartyOrder=r.id;const dialog=$('#third-party-dialog');
 $('#third-party-form').reset();$('#third-party-hours').textContent=`${hours(r).toLocaleString('pt-BR')} h em ${day(r)} · ${weekLabel(week(r))}`;
 dialog.hidden=false;$('#third-party-name').focus();
}
function closeThirdPartyDialog(){thirdPartyOrder='';$('#third-party-dialog').hidden=true;}
$('#third-party-cancel').onclick=closeThirdPartyDialog;
$('#third-party-dialog').onclick=e=>{if(e.target.id==='third-party-dialog')closeThirdPartyDialog();};
$('#third-party-form').onsubmit=e=>{e.preventDefault();const r=ORDER_MAP.get(thirdPartyOrder);if(!r)return closeThirdPartyDialog();const name=$('#third-party-name').value.trim(),company=$('#third-party-company').value.trim(),registration=$('#third-party-registration').value.trim();if(!name||!company){toast('Informe o nome e a empresa do terceiro.');return;}const id=thirdPartyId(name,company,registration||name),allocationHours=hours(r),current=assignments(r);if(current.some(a=>a.id===id)){toast('Este terceiro já está na ordem.');return;}const total=dailyLoad(id,week(r),day(r),r.id)+allocationHours;if(total>8){toast(`${name} ultrapassaria o limite de 8 horas no dia.`);return;}saveAssignments(r,[...current,{id,hours:allocationHours,thirdParty:true,name,company,registration}]);markDirty(r);closeThirdPartyDialog();render(false);toast(`${name} · ${company} adicionado como obra de terceiro.`);};

window.SIMEC_SET_VIEW=setView;

$('#table-body').onclick=e=>{const stageButton=e.target.closest('[data-stage]'),extraButton=e.target.closest('[data-extra]'),addButton=e.target.closest('[data-add-labor]'),removeButton=e.target.closest('[data-remove-labor]'),saveButton=e.target.closest('[data-save]'),programButton=e.target.closest('[data-program]');
 if(stageButton){const r=ORDER_MAP.get(stageButton.dataset.order),current=CORE.indexOf(stage(r)),target=CORE.indexOf(stageButton.dataset.stage);if(!r)return;if(stageButton.dataset.stage==='04SC'){completeSchedule(r);return;}if(target>current+1){const required=CORE[current+1];toast(`Etapa bloqueada. Marque primeiro ${required} · ${CORE_LABEL[required]}.`);return;}if(target<=current){toast(`${stage(r)} já é a etapa atual desta ordem.`);return;}storage('stage',r.id,stageButton.dataset.stage);markDirty(r);const next=CORE[target+1];render(false);toast(next?`${stageButton.dataset.stage} marcada. Agora avance para ${next} e salve.`:`${stageButton.dataset.stage} marcada. Clique em Salvar tags.`);return;}
 if(extraButton){const r=ORDER_MAP.get(extraButton.dataset.order),name=extraButton.dataset.extra;if(!r)return;storage(name.toLowerCase(),r.id,flag(r,name)?'':'1');markDirty(r);render(false);toast(`Flag ${name} alterada. Clique em Salvar tags.`);return;}
 if(addButton){const r=ORDER_MAP.get(addButton.dataset.order),select=$(`[data-labor-select][data-order="${CSS.escape(r.id)}"]`),id=select?.value,allocationHours=hours(r);if(!id){toast('Selecione um profissional.');return;}if(id==='__third_party__'){openThirdPartyDialog(r);return;}if(!scheduleReady(r)){toast('Informe semana, dia e as horas desse profissional antes de adicioná-lo.');return;}const current=assignments(r);if(current.some(a=>a.id===id)){toast(`${personName(id)} já está nesta ordem.`);return;}const total=dailyLoad(id,week(r),day(r),r.id)+allocationHours;if(total>8){toast(`${personName(id)} ficaria com ${total.toLocaleString('pt-BR')} horas em ${day(r)}. O limite é 8 horas.`);return;}saveAssignments(r,[...current,{id,hours:allocationHours}]);markDirty(r);render(false);toast(`${personName(id)} adicionado com ${allocationHours.toLocaleString('pt-BR')} horas. Você pode ajustar as horas no cartão da pessoa.`);return;}
 if(removeButton){const r=ORDER_MAP.get(removeButton.dataset.order),id=removeButton.dataset.removeLabor;saveAssignments(r,assignments(r).filter(a=>a.id!==id));markDirty(r);render(false);toast(`${personName(id)} removido da ordem ${r.id}. Clique em Salvar tags.`);return;}
 if(saveButton){const r=ORDER_MAP.get(saveButton.dataset.order);if(!r)return;saveAudit(r);render(false);downloadSavedWorkbook();toast(`Ordem ${r.id} salva por ${currentUser().name}. Excel atualizado gerado.`);return;}
 if(programButton){completeSchedule(ORDER_MAP.get(programButton.dataset.order));return;}
};
$('#table-body').onchange=e=>{const order=e.target.dataset.order,r=ORDER_MAP.get(order);if(!r)return;if(e.target.matches('[data-assignment-hours]')){const id=String(e.target.dataset.person),value=Number(e.target.value),valid=scheduleIsValid(r,{assignmentId:id,assignmentHours:value});if(!valid.ok){toast(valid.message);render(false);return;}saveAssignments(r,assignments(r).map(a=>a.id===id?{...a,hours:value}:a));markDirty(r);render(false);return;}let prefix,value,next={};if(e.target.matches('[data-week]')){prefix='week';value=e.target.value;next.week=value;}else if(e.target.matches('[data-day]')){prefix='day';value=e.target.value;next.day=value;}else if(e.target.matches('[data-hours]')){prefix='hours';value=e.target.value;next.hours=value;}else return;const valid=scheduleIsValid(r,next);if(!valid.ok){toast(valid.message);render(false);return;}storage(prefix,r.id,value);markDirty(r);render(false);};

function exportRows(rows=selected()){return rows.map(r=>({
 ...r,stage:stage(r),stageDescription:CORE_LABEL[stage(r)]||'',flagSC:flag(r,'SC')?'SIM':'',flagGP:flag(r,'GP')?'SIM':'',flag05RS:flag(r,'05RS')?'SIM':'',flagAGCAD:flag(r,'AG-CAD')?'SIM':'',scheduledWeek:weekLabel(week(r)),scheduledDay:day(r),plannedHours:totalOrderHours(r),labor:assignments(r).map(a=>allocationName(a)+(a.thirdParty&&a.company?` · ${a.company}`:'')).join(' | '),laborIds:assignments(r).map(a=>allocationCode(a)).join(' | '),laborHours:assignments(r).map(a=>`${allocationName(a)} (${allocationCode(a)}): ${a.hours.toLocaleString('pt-BR')}h`).join(' | '),pointing:isPointed(r)?'APONTADA':'AGUARDANDO ENCERRAMENTO',team:planningMeta(r).team,modifiedBy:audit(r)?.by||'',modifiedUser:audit(r)?.userId||'',modifiedAt:audit(r)?.at?new Date(audit(r).at).toLocaleString('pt-BR'):'',modifiedAction:audit(r)?.action||'',history:jsonStorage('history',r.id).map(x=>`${new Date(x.at).toLocaleString('pt-BR')} | ${x.by}${x.userId?' ('+x.userId+')':''} | ${x.action}`).join(' || '),
}));}
const EXPORT_COLUMNS=[['classification','Tipo'],['nature','Natureza'],['id','Ordem'],['plan','Plano'],['area','Área'],['assetCode','Bem'],['assetName','Nome do Bem'],['family','Família'],['costCenter','Centro de Custo'],['workCenter','Centro de Trabalho'],['specialty','Especialidade'],['description','Descrição da Ordem'],['service','Serviço / Manutenção'],['period','Periodicidade'],['system','Status Original'],[r=>dateText(r.date),'Data Original'],['age','Idade (Dias)'],['month','Mês'],['stage','Etapa'],['stageDescription','Descrição da Etapa'],['flagSC','Flag SC'],['flagGP','Flag GP'],['flag05RS','Flag 05RS - REPRG'],['flagAGCAD','Flag AG-CAD'],['scheduledWeek','Semana / Ano'],['scheduledDay','Dia'],['plannedHours','Horas Programadas'],['labor','Mão de Obra'],['laborIds','Matrículas'],['laborHours','Horas por funcionário'],['pointing','Apontamento'],['team','Equipe'],['modifiedBy','Modificado por'],['modifiedUser','Matrícula do modificador'],['modifiedAt','Modificado em'],['modifiedAction','Ação salva'],['history','Histórico de alterações']].map(([value,label])=>({value,label}));
function downloadSavedWorkbook(){const stamp=new Date().toISOString().replace(/[:T]/g,'-').slice(0,16);window.exportTableXlsx(exportRows(BACKLOG),EXPORT_COLUMNS,'Backlog_Programacao','SIMEC-Controle-Backlog-'+stamp+'.xlsx');}
function pointingExportRows(){return filteredPointRows().map(x=>({week:weekLabel(x.week),day:x.day,person:x.person.name,id:x.person.id,area:x.person.area,hours:x.hours,order:x.order.id,type:x.order.classification,specialty:x.order.specialty,orderStatus:x.order.system||x.order.status,pointing:x.pointed?'Apontada':'Aguardando encerramento',executors:x.order.executors||''}));}
const POINT_COLUMNS=[['week','Semana'],['day','Dia'],['person','Funcionário'],['id','Matrícula'],['area','Área do Funcionário'],['hours','Horas'],['order','Ordem'],['type','Tipo'],['specialty','Especialidade'],['orderStatus','Status da Ordem'],['pointing','Apontamento'],['executors','Executante na Base']].map(([value,label])=>({value,label}));

document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>setView(button.dataset.view));
$('#save-all').onclick=()=>{const rows=[...dirtyOrders].map(id=>ORDER_MAP.get(id)).filter(Boolean);if(!rows.length){toast('Não há alterações pendentes.');return;}rows.forEach(r=>saveAudit(r));render(false);downloadSavedWorkbook();toast(`${nf(rows.length)} ordem(ns) salvas por ${currentUser().name}. Excel atualizado gerado.`);};
$('#export-backlog').onclick=()=>window.exportTableXlsx(exportRows(),EXPORT_COLUMNS,'Backlog_Programacao','SIMEC-Backlog-Programacao-'+new Date().toISOString().slice(0,10)+'.xlsx');
$('#export-apontamentos').onclick=()=>window.exportTableXlsx(pointingExportRows(),POINT_COLUMNS,'Controle_Apontamentos','SIMEC-Controle-Apontamentos-'+new Date().toISOString().slice(0,10)+'.xlsx');
function finishPrint(){document.body.classList.remove('printing-schedule');}
$('#print-schedule').onclick=()=>{document.body.classList.add('printing-schedule');window.print();setTimeout(finishPrint,1500);};window.addEventListener('afterprint',finishPrint);$('#prev').onclick=()=>{page--;render(false);};$('#next').onclick=()=>{page++;render(false);};$('#reload').onclick=()=>location.reload();$('#updated').textContent='Dados extraídos em '+sourceDate.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});const adminTab=$('#admin-tab');function refreshAccess(){if(adminTab)adminTab.hidden=!ACCESS.isAdmin();render(false);}window.addEventListener('simec-authenticated',refreshAccess);if(adminTab)adminTab.hidden=!ACCESS.isAdmin();render();
